// Elemental Mayhem - Playable Elemental Classes & Dedicated Ability Kits
import { Unit, Ability, ElementType } from '../types';

export interface HeroClassConfig {
  element: ElementType;
  className: string;
  avatar: string;
  title: string;
  tagline: string;
  description: string;
  category: 'Primal' | 'Forces' | 'Life' | 'Cosmic';
  isStarter?: boolean;
  unlockRequirement?: string;
  bonusStats?: {
    maxHp?: number;
    maxAp?: number;
  };
  abilities: Ability[];
}

export const HERO_CLASSES: Record<ElementType, HeroClassConfig> = {
  // --- PRIMAL ELEMENTS ---
  Fire: {
    element: 'Fire',
    className: 'Pyromancer',
    avatar: '🔥',
    title: 'Master of Blazing Conflagration',
    tagline: 'Ignite enemies and scorch the battlefield with devastating heat.',
    description: 'Specializes in continuous burning damage, volcanic ground hazards, and volatile explosive reactions.',
    category: 'Primal',
    isStarter: true,
    abilities: [
      {
        id: 'flame_strike',
        name: 'Flame Strike',
        element: 'Fire',
        icon: '🗡️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Burning',
        statusDuration: 2,
        description: 'Strikes adjacent foe with burning elemental blade.',
        level: 1,
      },
      {
        id: 'fireball',
        name: 'Fireball',
        element: 'Fire',
        icon: '🔥',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        appliesStatus: 'Burning',
        statusDuration: 3,
        createsHazard: 'Burning',
        hazardDuration: 2,
        description: 'Hurls an explosive fireball that ignites targets and ground.',
        level: 1,
      },
      {
        id: 'combustion_wave',
        name: 'Combustion Wave',
        element: 'Fire',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 32,
        appliesStatus: 'Burning',
        statusDuration: 3,
        createsHazard: 'Burning',
        hazardDuration: 2,
        description: 'Sweeps an area with a wave of roaring combustion.',
        level: 1,
      },
      {
        id: 'inferno_pillar',
        name: 'Inferno Pillar',
        element: 'Fire',
        icon: '🌋',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 40,
        appliesStatus: 'Burning',
        statusDuration: 3,
        createsHazard: 'Burning',
        hazardDuration: 3,
        description: 'Calls down a towering pillar of raw infernal flame.',
        level: 1,
      },
    ],
  },

  Water: {
    element: 'Water',
    className: 'Hydromancer',
    avatar: '💧',
    title: 'Master of Tidal Deluge',
    tagline: 'Drench the arena with high-pressure torrents and puddles.',
    description: 'Excels at soaking targets, washing away burning tiles, creating puddle conduits, and massive hydro-impacts.',
    category: 'Primal',
    isStarter: true,
    abilities: [
      {
        id: 'water_whip',
        name: 'Water Whip',
        element: 'Water',
        icon: '🌊',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 15,
        appliesStatus: 'Wet',
        statusDuration: 2,
        description: 'Lashes enemies with a pressurized stream of water.',
        level: 1,
      },
      {
        id: 'water_torrent',
        name: 'Water Torrent',
        element: 'Water',
        icon: '💧',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 22,
        appliesStatus: 'Wet',
        statusDuration: 3,
        createsHazard: 'Puddle',
        hazardDuration: 3,
        description: 'Blasts pressurized water, soaking targets and creating puddles.',
        level: 1,
      },
      {
        id: 'tidal_surge',
        name: 'Tidal Surge',
        element: 'Water',
        icon: '🌊',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'Wet',
        statusDuration: 3,
        createsHazard: 'Puddle',
        hazardDuration: 3,
        description: 'Surging wave drenching multiple tiles.',
        level: 1,
      },
      {
        id: 'glacial_deluge',
        name: 'Glacial Deluge',
        element: 'Water',
        icon: '🧊',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        appliesStatus: 'Wet',
        statusDuration: 3,
        createsHazard: 'Puddle',
        hazardDuration: 4,
        description: 'Submerges the target zone under freezing deluge.',
        level: 1,
      },
    ],
  },

  Earth: {
    element: 'Earth',
    className: 'Terramancer',
    avatar: '🪨',
    title: 'Master of Tectonic Fortitude',
    tagline: 'Shatter the arena ground, root enemies, and crush with stone.',
    description: 'Possesses +20 bonus maximum HP, heavy physical impact, obstacle manipulation, and unbreakable rooting.',
    category: 'Primal',
    isStarter: true,
    bonusStats: {
      maxHp: 120,
    },
    abilities: [
      {
        id: 'stone_fist',
        name: 'Stone Fist',
        element: 'Earth',
        icon: '👊',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Heavy fist formed of solid bedrock.',
        level: 1,
      },
      {
        id: 'rock_barrage',
        name: 'Rock Barrage',
        element: 'Earth',
        icon: '🪨',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Hurls jagged rocks that pin and root the target.',
        level: 1,
      },
      {
        id: 'tectonic_quake',
        name: 'Tectonic Quake',
        element: 'Earth',
        icon: '🌋',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 32,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Shatters the ground, rooting all foes in the area.',
        level: 1,
      },
      {
        id: 'monolith_crusher',
        name: 'Monolith Crusher',
        element: 'Earth',
        icon: '🗿',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 42,
        description: 'Drops a massive prehistoric monolith on the target.',
        level: 1,
      },
    ],
  },

  Wind: {
    element: 'Wind',
    className: 'Windwalker',
    avatar: '💨',
    title: 'Master of Gale & Vortex',
    tagline: 'Slice with aerodynamic velocity and blow away battlefield hazards.',
    description: 'High AP efficiency, ranged gale slices, and ability to fan flames into raging firestorms.',
    category: 'Primal',
    unlockRequirement: '👑 Admin Exclusive (Unobtainable by Players)',
    abilities: [
      {
        id: 'wind_cutter',
        name: 'Wind Cutter',
        element: 'Wind',
        icon: '🗡️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Swift compressed gust blade.',
        level: 1,
      },
      {
        id: 'gust_blast',
        name: 'Gust Blast',
        element: 'Wind',
        icon: '💨',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        description: 'Concussive air blast knocking enemies back.',
        level: 1,
      },
      {
        id: 'cyclonic_fury',
        name: 'Cyclonic Fury',
        element: 'Wind',
        icon: '🌪️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 34,
        description: 'Summons raging vortex blades that shred defenses.',
        level: 1,
      },
      {
        id: 'typhoon_cataclysm',
        name: 'Typhoon Cataclysm',
        element: 'Wind',
        icon: '🌀',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 42,
        description: 'Unleashes a hurricane-force tempest.',
        level: 1,
      },
    ],
  },

  Sky: {
    element: 'Sky',
    className: 'Skylord',
    avatar: '☁️',
    title: 'Sovereign of the Stratosphere',
    tagline: 'Ascend above ground perils and strike with aerial supremacy.',
    description: 'Specializes in high vertical strikes, clearing ground hazards, and atmospheric blasts.',
    category: 'Primal',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'gale_slash',
        name: 'Gale Slash',
        element: 'Sky',
        icon: '🪶',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Feather-light supersonic slash.',
        level: 1,
      },
      {
        id: 'cloud_burst',
        name: 'Cloud Burst',
        element: 'Sky',
        icon: '☁️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        description: 'Pressurized cloud burst disorienting the target.',
        level: 1,
      },
      {
        id: 'stratospheric_tempest',
        name: 'Stratospheric Tempest',
        element: 'Sky',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Brings down high-altitude storm fury.',
        level: 1,
      },
      {
        id: 'celestial_descent',
        name: 'Celestial Descent',
        element: 'Sky',
        icon: '🦅',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 44,
        description: 'Dives from high stratosphere with devastating impact.',
        level: 1,
      },
    ],
  },

  Ice: {
    element: 'Ice',
    className: 'Cryomancer',
    avatar: '❄️',
    title: 'Master of Absolute Zero',
    tagline: 'Freeze wet targets solid and shatter crystalline ice for bonus damage.',
    description: 'Dominates crowd control by freezing enemies, halting AP generation, and inflicting shatter combos.',
    category: 'Primal',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'icicle_javelin',
        name: 'Icicle Javelin',
        element: 'Ice',
        icon: '🗡️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Frozen',
        statusDuration: 1,
        description: 'Hurls needle-sharp icicle piercing armor.',
        level: 1,
      },
      {
        id: 'frost_nova',
        name: 'Frost Nova',
        element: 'Ice',
        icon: '❄️',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 24,
        appliesStatus: 'Frozen',
        statusDuration: 2,
        description: 'Explosion of frost freezing all targets in area.',
        level: 1,
      },
      {
        id: 'glacial_burst',
        name: 'Glacial Burst',
        element: 'Ice',
        icon: '🧊',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        appliesStatus: 'Frozen',
        statusDuration: 2,
        createsHazard: 'IceSurface',
        hazardDuration: 3,
        description: 'Erupts massive glaciers that deal heavy frost damage.',
        level: 1,
      },
      {
        id: 'absolute_zero',
        name: 'Absolute Zero',
        element: 'Ice',
        icon: '🥶',
        apCost: 3,
        cooldown: 2,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        appliesStatus: 'Frozen',
        statusDuration: 3,
        description: 'Drops molecular motion to absolute zero.',
        level: 1,
      },
    ],
  },

  Magma: {
    element: 'Magma',
    className: 'Magmamancer',
    avatar: '🌋',
    title: 'Master of Molten Volcanism',
    tagline: 'Combine fire and molten stone to flood the grid with lava pools.',
    description: 'Heavy thermal destruction leaving long-lasting lava pools and burning reactions.',
    category: 'Primal',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'magma_clot',
        name: 'Magma Clot',
        element: 'Magma',
        icon: '☄️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        appliesStatus: 'Burning',
        statusDuration: 2,
        description: 'Throws a lump of molten slag.',
        level: 1,
      },
      {
        id: 'molten_eruption',
        name: 'Molten Eruption',
        element: 'Magma',
        icon: '🌋',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        createsHazard: 'LavaPool',
        hazardDuration: 3,
        description: 'Erupts boiling magma under target.',
        level: 1,
      },
      {
        id: 'lava_surge',
        name: 'Lava Surge',
        element: 'Magma',
        icon: '🔥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        appliesStatus: 'Burning',
        statusDuration: 3,
        createsHazard: 'LavaPool',
        hazardDuration: 3,
        description: 'Surges rivers of lava through target area.',
        level: 1,
      },
      {
        id: 'volcanic_cataclysm',
        name: 'Volcanic Cataclysm',
        element: 'Magma',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        createsHazard: 'LavaPool',
        hazardDuration: 4,
        description: 'Triggers a supervolcano cataclysm.',
        level: 1,
      },
    ],
  },

  Crystal: {
    element: 'Crystal',
    className: 'Crystallomancer',
    avatar: '💎',
    title: 'Master of Prismatic Resonance',
    tagline: 'Pierce magical defenses and reflect beams with crystalline geometry.',
    description: 'High armor penetration, refractive spell amplification, and sharp crystal spikes.',
    category: 'Primal',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'crystal_shard',
        name: 'Crystal Shard',
        element: 'Crystal',
        icon: '💎',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Launches a razor-sharp diamond needle.',
        level: 1,
      },
      {
        id: 'prism_beam',
        name: 'Prism Beam',
        element: 'Crystal',
        icon: '✨',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 27,
        description: 'Refracts blinding beam of concentrated prismatic light.',
        level: 1,
      },
      {
        id: 'crystal_spikes',
        name: 'Crystal Spikes',
        element: 'Crystal',
        icon: '💠',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        createsHazard: 'CrystalSpikes',
        hazardDuration: 3,
        description: 'Erupts field of jagged crystal spikes.',
        level: 1,
      },
      {
        id: 'diamond_shatter',
        name: 'Diamond Shatter',
        element: 'Crystal',
        icon: '💎',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Detonates crystal lattice with overwhelming force.',
        level: 1,
      },
    ],
  },

  // --- FORCES & ENERGY ---
  Lightning: {
    element: 'Lightning',
    className: 'Stormcaller',
    avatar: '⚡',
    title: 'Master of Ionized Tempest',
    tagline: 'Electrify wet surfaces and shock foes with instantaneous voltage.',
    description: 'Deploys long-range lightning, chaining shocks, AP denial, and lethal electrified puddle combos.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'spark_jab',
        name: 'Spark Jab',
        element: 'Lightning',
        icon: '⚡',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Shocked',
        statusDuration: 2,
        description: 'Quick jolt of static voltage.',
        level: 1,
      },
      {
        id: 'lightning_bolt',
        name: 'Lightning Bolt',
        element: 'Lightning',
        icon: '⚡',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 30,
        appliesStatus: 'Shocked',
        statusDuration: 2,
        description: 'Strikes ionized lightning, shocking targets and electrifying water.',
        level: 1,
      },
      {
        id: 'chain_overload',
        name: 'Chain Overload',
        element: 'Lightning',
        icon: '🌩️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 35,
        appliesStatus: 'Shocked',
        statusDuration: 2,
        createsHazard: 'ElectrifiedPuddle',
        hazardDuration: 2,
        description: 'Overcharges the area, chaining voltage across targets.',
        level: 1,
      },
      {
        id: 'thunder_cataclysm',
        name: 'Thunder Cataclysm',
        element: 'Lightning',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 44,
        appliesStatus: 'Shocked',
        statusDuration: 3,
        description: 'Calls down heaven-rending thunderstorm destruction.',
        level: 1,
      },
    ],
  },

  Thunder: {
    element: 'Thunder',
    className: 'Thundercaller',
    avatar: '⚡',
    title: 'Master of Acoustic Detonation',
    tagline: 'Deafen and daze enemies with concussive sonic booms.',
    description: 'High burst damage that dazes enemies, reduces AP, and shatters brittle frozen defenses.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'thunder_clap',
        name: 'Thunder Clap',
        element: 'Thunder',
        icon: '👏',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        appliesStatus: 'Stunned',
        statusDuration: 1,
        description: 'Deafening hand clap bursting ear drums.',
        level: 1,
      },
      {
        id: 'sonic_boom',
        name: 'Sonic Boom',
        element: 'Thunder',
        icon: '💥',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 28,
        description: 'Supersonic shockwave pushing enemies.',
        level: 1,
      },
      {
        id: 'thunderous_smite',
        name: 'Thunderous Smite',
        element: 'Thunder',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        description: 'Concussive smite vibrating ground to dust.',
        level: 1,
      },
      {
        id: 'roar_of_the_heavens',
        name: 'Roar of the Heavens',
        element: 'Thunder',
        icon: '📢',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        description: 'Apocalyptic thunder that shatters target sanity and armor.',
        level: 1,
      },
    ],
  },

  Storm: {
    element: 'Storm',
    className: 'Stormbringer',
    avatar: '⛈️',
    title: 'Master of Tempestuous Deluge',
    tagline: 'Combine rain deluge, roaring wind, and lightning bolts into unified storms.',
    description: 'Multi-element synergies that simultaneously soak and shock enemy formations.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'storm_jolt',
        name: 'Storm Jolt',
        element: 'Storm',
        icon: '⚡',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Shocked',
        statusDuration: 2,
        description: 'Jolt of static storm charge.',
        level: 1,
      },
      {
        id: 'tempest_surge',
        name: 'Tempest Surge',
        element: 'Storm',
        icon: '⛈️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'Wet',
        statusDuration: 3,
        createsHazard: 'ElectrifiedPuddle',
        hazardDuration: 2,
        description: 'Drenches and electrifies target location.',
        level: 1,
      },
      {
        id: 'maelstrom_burst',
        name: 'Maelstrom Burst',
        element: 'Storm',
        icon: '🌪️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        description: 'Whirling vortex of rain and electrical arcs.',
        level: 1,
      },
      {
        id: 'cyclonic_maelstrom',
        name: 'Cyclonic Maelstrom',
        element: 'Storm',
        icon: '⛈️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        createsHazard: 'ElectrifiedPuddle',
        hazardDuration: 3,
        description: 'Apocalyptic supercell lightning storm.',
        level: 1,
      },
    ],
  },

  Metal: {
    element: 'Metal',
    className: 'Ironclad',
    avatar: '🛡️',
    title: 'Master of Ferromagnetic Armor',
    tagline: 'Impenetrable defense, blade strikes, and crushing heavy armor.',
    description: 'Possesses +30 bonus HP, physical damage mitigation, and devastating armor-shattering strikes.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 5 Boss',
    bonusStats: {
      maxHp: 130,
    },
    abilities: [
      {
        id: 'steel_slash',
        name: 'Steel Slash',
        element: 'Metal',
        icon: '⚔️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Sharp tempered blade slash.',
        level: 1,
      },
      {
        id: 'iron_spike',
        name: 'Iron Spike',
        element: 'Metal',
        icon: '🗡️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Launches reinforced iron javelin.',
        level: 1,
      },
      {
        id: 'magnetic_repulsion',
        name: 'Magnetic Repulsion',
        element: 'Metal',
        icon: '🛡️',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 28,
        appliesStatus: 'Shielded',
        statusDuration: 2,
        description: 'Shields hero and pushes away metallic foes.',
        level: 1,
      },
      {
        id: 'titanium_fortress',
        name: 'Titanium Fortress',
        element: 'Metal',
        icon: '🏰',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 44,
        description: 'Crushes targets under tons of solid titanium.',
        level: 1,
      },
    ],
  },

  Magnetism: {
    element: 'Magnetism',
    className: 'Magnetomancer',
    avatar: '🧲',
    title: 'Master of Bipolar Polarity',
    tagline: 'Manipulate magnetic polarity to pull enemies into hazards and crush metallic foes.',
    description: 'Positional control, magnetic clustering, and electrical chain synergies.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'magnetic_jolt',
        name: 'Magnetic Jolt',
        element: 'Magnetism',
        icon: '🧲',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Polarizes target with magnetic charge.',
        level: 1,
      },
      {
        id: 'polarity_pull',
        name: 'Polarity Pull',
        element: 'Magnetism',
        icon: '🧲',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        description: 'Yanks enemy across the grid toward the caster.',
        level: 1,
      },
      {
        id: 'iron_storm',
        name: 'Iron Storm',
        element: 'Magnetism',
        icon: '🌪️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Swirls magnetized metal fragments into a blender of death.',
        level: 1,
      },
      {
        id: 'emp_blast',
        name: 'Electromagnetic Pulse',
        element: 'Magnetism',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        appliesStatus: 'Shocked',
        statusDuration: 3,
        description: 'Overwhelming electromagnetic pulse draining enemy energy.',
        level: 1,
      },
    ],
  },

  Sound: {
    element: 'Sound',
    className: 'Sonomancer',
    avatar: '🔊',
    title: 'Master of Acoustic Resonance',
    tagline: 'Disrupt enemy rhythm with sonic shockwaves and shatter crystal structures.',
    description: 'Acoustic disruption, disorienting audio frequencies, and devastating sound waves.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'sonic_pulse',
        name: 'Sonic Pulse',
        element: 'Sound',
        icon: '🔈',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Piercing acoustic vibration pulse.',
        level: 1,
      },
      {
        id: 'resonance_blast',
        name: 'Resonance Blast',
        element: 'Sound',
        icon: '🔉',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Hits the target with their resonant frequency.',
        level: 1,
      },
      {
        id: 'acoustic_rupture',
        name: 'Acoustic Rupture',
        element: 'Sound',
        icon: '🔊',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Shatters bones and physical structures with high decibels.',
        level: 1,
      },
      {
        id: 'symphonic_crescendo',
        name: 'Symphonic Crescendo',
        element: 'Sound',
        icon: '🎵',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Unleashes an overwhelming sonic orchestra blast.',
        level: 1,
      },
    ],
  },

  Force: {
    element: 'Force',
    className: 'Kineticist',
    avatar: '💥',
    title: 'Master of Kinetic Impact',
    tagline: 'Slam enemies across the arena and crush obstacles with sheer momentum.',
    description: 'Kinetic displacement, armor breaking, and heavy blunt force trauma.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'force_jab',
        name: 'Force Jab',
        element: 'Force',
        icon: '👊',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Concentrated kinetic punch.',
        level: 1,
      },
      {
        id: 'force_push',
        name: 'Force Push',
        element: 'Force',
        icon: '✋',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        description: 'Knocks enemy back into walls or hazards.',
        level: 1,
      },
      {
        id: 'kinetic_shockwave',
        name: 'Kinetic Shockwave',
        element: 'Force',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Ground-slam releasing devastating kinetic wave.',
        level: 1,
      },
      {
        id: 'crushing_impact',
        name: 'Crushing Impact',
        element: 'Force',
        icon: '🔨',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Crushes targets under megatons of kinetic force.',
        level: 1,
      },
    ],
  },

  Energy: {
    element: 'Energy',
    className: 'Energy Conduit',
    avatar: '⚡',
    title: 'Master of Pure Plasma',
    tagline: 'Channel raw concentrated energy beams that incinerate all defenses.',
    description: 'High range, pinpoint linear penetration, and overwhelming damage output.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'energy_spark',
        name: 'Energy Spark',
        element: 'Energy',
        icon: '✨',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        description: 'Quick beam of concentrated plasma.',
        level: 1,
      },
      {
        id: 'plasma_beam',
        name: 'Plasma Beam',
        element: 'Energy',
        icon: '⚡',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 28,
        description: 'Piercing lance of pure energy.',
        level: 1,
      },
      {
        id: 'energy_discharge',
        name: 'Energy Discharge',
        element: 'Energy',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        description: 'Discharges overcharged plasma reactor in an area.',
        level: 1,
      },
      {
        id: 'supercharged_nova',
        name: 'Supercharged Nova',
        element: 'Energy',
        icon: '🌟',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 47,
        description: 'Unleashes the raw power of a fusion reactor.',
        level: 1,
      },
    ],
  },

  // --- LIFE & NATURE ---
  Nature: {
    element: 'Nature',
    className: 'Druid',
    avatar: '🌿',
    title: 'Warden of Thorns & Flora',
    tagline: 'Entangle enemies in thorny vines and cultivate biological resurgence.',
    description: 'Roots foes with thorns, siphons biological health, and blooms restorative nature aura.',
    category: 'Life',
    isStarter: true,
    abilities: [
      {
        id: 'thorn_whip',
        name: 'Thorn Whip',
        element: 'Nature',
        icon: '🌿',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 15,
        appliesStatus: 'Rooted',
        statusDuration: 1,
        description: 'Lashes with barbed vines.',
        level: 1,
      },
      {
        id: 'bramble_trap',
        name: 'Bramble Trap',
        element: 'Nature',
        icon: '🌾',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 23,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Entangles target in razor brambles.',
        level: 1,
      },
      {
        id: 'flora_surge',
        name: 'Flora Surge',
        element: 'Nature',
        icon: '🌺',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 32,
        appliesStatus: 'Regenerating',
        statusDuration: 3,
        description: 'Blooms healing flora while damaging foes.',
        level: 1,
      },
      {
        id: 'wrath_of_nature',
        name: 'Wrath of Nature',
        element: 'Nature',
        icon: '🌳',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 42,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Ancient primeval forest awakens to crush all foes.',
        level: 1,
      },
    ],
  },

  Life: {
    element: 'Life',
    className: 'Biomancer',
    avatar: '🌱',
    title: 'Master of Vitality & Regrowth',
    tagline: 'Sustain boundless health regeneration and purge toxic corruption.',
    description: 'High HP pool, sustained regeneration, status cleansing, and radiant life bursts.',
    category: 'Life',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    bonusStats: {
      maxHp: 120,
    },
    abilities: [
      {
        id: 'vital_strike',
        name: 'Vital Strike',
        element: 'Life',
        icon: '🌱',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Regenerating',
        statusDuration: 2,
        description: 'Infuses vital sap dealing damage and restoring health.',
        level: 1,
      },
      {
        id: 'regrowth_bloom',
        name: 'Regrowth Bloom',
        element: 'Life',
        icon: '🌸',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        appliesStatus: 'Regenerating',
        statusDuration: 3,
        description: 'Restores vitality while shocking necrotic enemies.',
        level: 1,
      },
      {
        id: 'solar_synthesis',
        name: 'Solar Synthesis',
        element: 'Life',
        icon: '☀️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 34,
        description: 'Converts sunlight into overwhelming cellular burst.',
        level: 1,
      },
      {
        id: 'breath_of_life',
        name: 'Breath of Life',
        element: 'Life',
        icon: '✨',
        apCost: 3,
        cooldown: 2,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 44,
        description: 'Primeval pulse of creation extinguishing undead and foes.',
        level: 1,
      },
      {
        id: 'unzombify_burst',
        name: 'Unzombify Explosion',
        element: 'Life',
        icon: '🌟',
        apCost: 3,
        cooldown: 2,
        currentCooldown: 0,
        range: 6,
        aoeRadius: 1,
        targeting: 'AnyTile',
        baseDamage: 25,
        description: 'Unzombifies all zombies in a 3x3 area, triggering cascading blasts of Life that explode nearby zombies, and summons an agile Being of Life.',
        level: 1,
      },
    ],
  },

  Love: {
    element: 'Love',
    className: 'Amorist',
    avatar: '💖',
    title: 'Master of Heartfelt Charm',
    tagline: 'Charm foes into lowering their defenses and convert empathy into raw power.',
    description: 'Applies Charmed status, pacifies aggressive foes, and converts compassion into devastation.',
    category: 'Life',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'cupid_arrow',
        name: 'Cupid Arrow',
        element: 'Love',
        icon: '🏹',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Charmed',
        statusDuration: 2,
        description: 'Shoots an arrow of pure enchanted affection.',
        level: 1,
      },
      {
        id: 'heart_surge',
        name: 'Heart Surge',
        element: 'Love',
        icon: '💗',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        appliesStatus: 'Charmed',
        statusDuration: 2,
        description: 'Empathetic surge causing foe to hesitate.',
        level: 1,
      },
      {
        id: 'empathic_resonance',
        name: 'Empathic Resonance',
        element: 'Love',
        icon: '💓',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 35,
        description: 'Resonates feelings of overwhelming connection.',
        level: 1,
      },
      {
        id: 'charmed_singularity',
        name: 'Charmed Singularity',
        element: 'Love',
        icon: '💖',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        appliesStatus: 'Charmed',
        statusDuration: 3,
        description: 'Irresistible aura of pure universal love.',
        level: 1,
      },
    ],
  },

  Poison: {
    element: 'Poison',
    className: 'Venomancer',
    avatar: '🧪',
    title: 'Master of Corrosive Alchemy',
    tagline: 'Inflict stacking toxins and detonate caustic ground mire.',
    description: 'Masters lingering poison damage over time, toxic mire zones, and explosive fire reactions.',
    category: 'Life',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'toxic_sting',
        name: 'Toxic Sting',
        element: 'Poison',
        icon: '🦂',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 14,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        description: 'Stings with fast-acting neurotoxin.',
        level: 1,
      },
      {
        id: 'venom_spit',
        name: 'Venom Spit',
        element: 'Poison',
        icon: '🧪',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 20,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        createsHazard: 'ToxicMire',
        hazardDuration: 3,
        description: 'Spits corrosive venom creating Toxic Mire.',
        level: 1,
      },
      {
        id: 'toxic_cloud',
        name: 'Toxic Cloud',
        element: 'Poison',
        icon: '☁️',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        createsHazard: 'ToxicMire',
        hazardDuration: 3,
        description: 'Blasts an area with toxic spores.',
        level: 1,
      },
      {
        id: 'caustic_eruption',
        name: 'Caustic Eruption',
        element: 'Poison',
        icon: '☣️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        createsHazard: 'ToxicMire',
        hazardDuration: 3,
        description: 'Erupts concentrated acid that melts flesh and armor.',
        level: 1,
      },
    ],
  },

  Acid: {
    element: 'Acid',
    className: 'Acid Chemist',
    avatar: '🧪',
    title: 'Master of Caustic Dissolution',
    tagline: 'Melt metallic armor and dissolve defenses with concentrated acid.',
    description: 'High armor corrosion, dissolving physical obstacles, and hazardous acid pools.',
    category: 'Life',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'acid_dart',
        name: 'Acid Dart',
        element: 'Acid',
        icon: '🧪',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Corroded',
        statusDuration: 2,
        description: 'Fires vial of fluorosulfuric acid.',
        level: 1,
      },
      {
        id: 'corrosive_splash',
        name: 'Corrosive Splash',
        element: 'Acid',
        icon: '☣️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        createsHazard: 'AcidPool',
        hazardDuration: 3,
        description: 'Splashes acid, dissolving armor and ground.',
        level: 1,
      },
      {
        id: 'acid_pool_bomb',
        name: 'Acid Pool Bomb',
        element: 'Acid',
        icon: '💣',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 34,
        createsHazard: 'AcidPool',
        hazardDuration: 3,
        description: 'Floods area with high-strength acid pool.',
        level: 1,
      },
      {
        id: 'melting_cascade',
        name: 'Melting Cascade',
        element: 'Acid',
        icon: '☢️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 43,
        appliesStatus: 'Corroded',
        statusDuration: 3,
        description: 'Total chemical liquefaction of target defenses.',
        level: 1,
      },
    ],
  },

  Blood: {
    element: 'Blood',
    className: 'Hemomancer',
    avatar: '🩸',
    title: 'Master of Sanguine Siphon',
    tagline: 'Inflict bleeding on foes and fuel devastating sanguine eruptions.',
    description: 'Applies bleeding damage over time, lifesteal mechanics, and sacrifice burst damage.',
    category: 'Life',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'blood_blade',
        name: 'Blood Blade',
        element: 'Blood',
        icon: '🗡️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        appliesStatus: 'Bleeding',
        statusDuration: 2,
        description: 'Coagulated blood dagger inflicting bleed.',
        level: 1,
      },
      {
        id: 'siphon_torrent',
        name: 'Siphon Torrent',
        element: 'Blood',
        icon: '🩸',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        description: 'Siphons target vitality back to hero.',
        level: 1,
      },
      {
        id: 'crimson_explosion',
        name: 'Crimson Explosion',
        element: 'Blood',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        appliesStatus: 'Bleeding',
        statusDuration: 3,
        description: 'Detonates sanguine essence across multiple tiles.',
        level: 1,
      },
      {
        id: 'exsanguination',
        name: 'Exsanguination',
        element: 'Blood',
        icon: '🩸',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Rips all blood from target veins in lethal execute.',
        level: 1,
      },
    ],
  },

  // --- COSMIC & OCCULT ---
  Light: {
    element: 'Light',
    className: 'Luminary',
    avatar: '☀️',
    title: 'Master of Solar Radiance',
    tagline: 'Purge darkness with solar rays and blind foes with brilliant light.',
    description: 'Blinds enemies, deals bonus damage to undead/darkness, and creates solar flares.',
    category: 'Cosmic',
    isStarter: true,
    abilities: [
      {
        id: 'holy_ray',
        name: 'Holy Ray',
        element: 'Light',
        icon: '✨',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Blinded',
        statusDuration: 1,
        description: 'Piercing ray of pure sunlight.',
        level: 1,
      },
      {
        id: 'solar_flare',
        name: 'Solar Flare',
        element: 'Light',
        icon: '☀️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 27,
        appliesStatus: 'Blinded',
        statusDuration: 2,
        description: 'Blinds target and burns dark entities.',
        level: 1,
      },
      {
        id: 'prismatic_beam',
        name: 'Prismatic Beam',
        element: 'Light',
        icon: '🌈',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 37,
        description: 'Wide beam of refracted pure light.',
        level: 1,
      },
      {
        id: 'supernova_radiance',
        name: 'Supernova Radiance',
        element: 'Light',
        icon: '🌟',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        description: 'Miniature supernova banishing all shadows.',
        level: 1,
      },
    ],
  },

  Darkness: {
    element: 'Darkness',
    className: 'Shadowmancer',
    avatar: '🌑',
    title: 'Master of Umbral Nightfall',
    tagline: 'Shroud the battlefield in shadows and execute foes from the dark.',
    description: 'Life drain, darkness shrouding, and annihilation combos when paired with light.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'shadow_strike',
        name: 'Shadow Strike',
        element: 'Darkness',
        icon: '🗡️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        description: 'Strikes from the umbral shadows.',
        level: 1,
      },
      {
        id: 'umbral_grasp',
        name: 'Umbral Grasp',
        element: 'Darkness',
        icon: '🌑',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'VoidMarked',
        statusDuration: 2,
        description: 'Shadow hands drag target and apply mark.',
        level: 1,
      },
      {
        id: 'nightfall_eruption',
        name: 'Nightfall Eruption',
        element: 'Darkness',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 37,
        description: 'Erupts geysers of dark matter.',
        level: 1,
      },
      {
        id: 'abyssal_eclipse',
        name: 'Abyssal Eclipse',
        element: 'Darkness',
        icon: '🌑',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        description: 'Total solar eclipse devouring enemy life.',
        level: 1,
      },
    ],
  },

  Void: {
    element: 'Void',
    className: 'Void Sage',
    avatar: '🌌',
    title: 'Master of Entropic Singularity',
    tagline: 'Tear reality, apply void marks, and collapse space-time.',
    description: 'Wields the ultimate entropic power of reality collapse, void rifts, and high elemental dominance.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Supreme Boss (The Void Archon)',
    abilities: [
      {
        id: 'null_touch',
        name: 'Null Touch',
        element: 'Void',
        icon: '🟣',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 15,
        appliesStatus: 'VoidMarked',
        statusDuration: 2,
        description: 'Touches the target with pure anti-matter.',
        level: 1,
      },
      {
        id: 'void_lance',
        name: 'Void Lance',
        element: 'Void',
        icon: '🌌',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'VoidMarked',
        statusDuration: 3,
        description: 'Penetrating lance of concentrated void energy.',
        level: 1,
      },
      {
        id: 'void_rupture',
        name: 'Void Rupture',
        element: 'Void',
        icon: '🔮',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        appliesStatus: 'VoidMarked',
        statusDuration: 3,
        createsHazard: 'VoidRift',
        hazardDuration: 3,
        description: 'Ruptures reality for high entropic burst and void rifts.',
        level: 1,
      },
      {
        id: 'cosmic_singularity',
        name: 'Cosmic Singularity',
        element: 'Void',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        appliesStatus: 'VoidMarked',
        statusDuration: 3,
        createsHazard: 'VoidRift',
        hazardDuration: 3,
        description: 'Summons a gravitational anomaly that crushes reality.',
        level: 1,
      },
    ],
  },

  Chaos: {
    element: 'Chaos',
    className: 'Chaos Mage',
    avatar: '🌀',
    title: 'Master of Entropic Flux',
    tagline: 'Bend probability, unleash unpredictable elemental cascades, and shatter order.',
    description: 'Randomized elemental damage bursts, chaotic status application, and high critical potential.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'chaos_bolt',
        name: 'Chaos Bolt',
        element: 'Chaos',
        icon: '🌀',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Bolt of unpredictable elemental energy.',
        level: 1,
      },
      {
        id: 'entropy_flux',
        name: 'Entropy Flux',
        element: 'Chaos',
        icon: '🎲',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 28,
        description: 'Rolls the dice of fate dealing high variable damage.',
        level: 1,
      },
      {
        id: 'warp_singularity',
        name: 'Warp Singularity',
        element: 'Chaos',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        description: 'Warps local physics into pandemonium.',
        level: 1,
      },
      {
        id: 'pandemonium_burst',
        name: 'Pandemonium Burst',
        element: 'Chaos',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 47,
        description: 'Unleashes pure unadulterated cosmic chaos.',
        level: 1,
      },
    ],
  },

  Time: {
    element: 'Time',
    className: 'Chronomancer',
    avatar: '⏳',
    title: 'Master of Temporal Flux',
    tagline: 'Bend turns, refund AP, and age enemies into dust.',
    description: 'AP refund mechanics, cooldown acceleration, temporal slow, and timeline distortion.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'temporal_jab',
        name: 'Temporal Jab',
        element: 'Time',
        icon: '⏳',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Fast strike arriving from the future.',
        level: 1,
      },
      {
        id: 'time_warp',
        name: 'Time Warp',
        element: 'Time',
        icon: '⌛',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'TimeDilation',
        statusDuration: 2,
        description: 'Slows enemy actions and accelerates player.',
        level: 1,
      },
      {
        id: 'decay_pulse',
        name: 'Decay Pulse',
        element: 'Time',
        icon: '🕒',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Ages all foes in the area by centuries.',
        level: 1,
      },
      {
        id: 'chronos_stasis',
        name: 'Chronos Stasis',
        element: 'Time',
        icon: '⏱️',
        apCost: 3,
        cooldown: 2,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        appliesStatus: 'Stunned',
        statusDuration: 2,
        description: 'Freezes target timeline completely in stasis.',
        level: 1,
      },
    ],
  },

  Space: {
    element: 'Space',
    className: 'Cosmomancer',
    avatar: '🌌',
    title: 'Master of Spatial Topology',
    tagline: 'Tear coordinate rifts and collapse dimensional distances.',
    description: 'Teleportation, coordinate displacement, and black hole gravitation.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'space_tear',
        name: 'Space Tear',
        element: 'Space',
        icon: '🌌',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Tears fabric of space dealing direct damage.',
        level: 1,
      },
      {
        id: 'dimensional_warp',
        name: 'Dimensional Warp',
        element: 'Space',
        icon: '🌀',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Warps space around foe, dropping them on new coordinates.',
        level: 1,
      },
      {
        id: 'spatial_rift',
        name: 'Spatial Rift',
        element: 'Space',
        icon: '🔮',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 37,
        createsHazard: 'VoidRift',
        hazardDuration: 3,
        description: 'Opens persistent spatial tear.',
        level: 1,
      },
      {
        id: 'event_horizon',
        name: 'Event Horizon',
        element: 'Space',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        description: 'Crushes targets past the point of no return.',
        level: 1,
      },
    ],
  },

  Death: {
    element: 'Death',
    className: 'Reaper',
    avatar: '💀',
    title: 'Harvester of Mortals',
    tagline: 'Reap low-health souls and execute foes with necrotic finality.',
    description: 'Execute mechanics on targets under 30% HP, soul siphoning, and corpse detonation.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'reaper_scythe',
        name: 'Reaper Scythe',
        element: 'Death',
        icon: '🗡️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Sweeps ethereal death scythe.',
        level: 1,
      },
      {
        id: 'soul_drain',
        name: 'Soul Drain',
        element: 'Death',
        icon: '💀',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Rips soul fragments, dealing necrotic damage.',
        level: 1,
      },
      {
        id: 'corpse_nova',
        name: 'Corpse Nova',
        element: 'Death',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        description: 'Detonates death energy across area.',
        level: 1,
      },
      {
        id: 'grave_cataclysm',
        name: 'Grave Cataclysm',
        element: 'Death',
        icon: '☠️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 47,
        description: 'Opens gates of the underworld.',
        level: 1,
      },
    ],
  },

  Soul: {
    element: 'Soul',
    className: 'Soulbinder',
    avatar: '👻',
    title: 'Master of Spectral Binding',
    tagline: 'Pierce physical armor by attacking the spirit directly.',
    description: 'Direct health piercing, spectral chains, and ghost summons.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'soul_spike',
        name: 'Soul Spike',
        element: 'Soul',
        icon: '👻',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Direct spirit needle ignoring physical armor.',
        level: 1,
      },
      {
        id: 'ghostly_wail',
        name: 'Ghostly Wail',
        element: 'Soul',
        icon: '🗣️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        description: 'Terrifying wail stunning target mind.',
        level: 1,
      },
      {
        id: 'soul_shackle',
        name: 'Soul Shackle',
        element: 'Soul',
        icon: '⛓️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Binds enemy souls with spectral chains.',
        level: 1,
      },
      {
        id: 'astral_rupture',
        name: 'Astral Rupture',
        element: 'Soul',
        icon: '✨',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Tears astral plane in massive soul eruption.',
        level: 1,
      },
    ],
  },

  Spirit: {
    element: 'Spirit',
    className: 'Shaman',
    avatar: '✨',
    title: 'Master of Ancestral Guardians',
    tagline: 'Summon guardian spirits to shield allies and unleash ethereal wrath.',
    description: 'Spectral shielding, ancestor guidance, and ethereal burst damage.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'spirit_arrow',
        name: 'Spirit Arrow',
        element: 'Spirit',
        icon: '🏹',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Fires arrow of glowing ancestral energy.',
        level: 1,
      },
      {
        id: 'ethereal_blast',
        name: 'Ethereal Blast',
        element: 'Spirit',
        icon: '✨',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Blasts enemy with spiritual force.',
        level: 1,
      },
      {
        id: 'ancestral_wrath',
        name: 'Ancestral Wrath',
        element: 'Spirit',
        icon: '🛡️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Summons ancestral spirits to wrathfully strike.',
        level: 1,
      },
      {
        id: 'spiritual_ascendance',
        name: 'Spiritual Ascendance',
        element: 'Spirit',
        icon: '🌟',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Ascends into pure spirit avatar of devastation.',
        level: 1,
      },
    ],
  },

  // Fallbacks for remaining elements in 42
  Electricity: {
    element: 'Electricity',
    className: 'Volt Specialist',
    avatar: '⚡',
    title: 'Master of Continuous Current',
    tagline: 'Chain high voltage circuits across wet ground.',
    description: 'Chaining shocks and electrifying water.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'volt_zap',
        name: 'Volt Zap',
        element: 'Electricity',
        icon: '⚡',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Shocked',
        statusDuration: 2,
        description: 'High voltage zap.',
        level: 1,
      },
      {
        id: 'current_beam',
        name: 'Current Beam',
        element: 'Electricity',
        icon: '⚡',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 28,
        description: 'Direct current arc.',
        level: 1,
      },
      {
        id: 'chain_discharge',
        name: 'Chain Discharge',
        element: 'Electricity',
        icon: '🌩️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Chains discharge across multiple targets.',
        level: 1,
      },
      {
        id: 'overvoltage_surge',
        name: 'Overvoltage Surge',
        element: 'Electricity',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Catastrophic circuit overvoltage.',
        level: 1,
      },
    ],
  },

  Order: {
    element: 'Order',
    className: 'Justiciar',
    avatar: '⚖️',
    title: 'Guardian of Immutable Law',
    tagline: 'Nullify chaos and lock enemy coordinates into strict order.',
    description: 'Cleanse debuffs and lock down targets.',
    category: 'Cosmic',
    unlockRequirement: 'Defeat Round 15 Final Boss',
    abilities: [
      {
        id: 'decree_of_order',
        name: 'Decree of Order',
        element: 'Order',
        icon: '⚖️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'Strikes with cosmic law.',
        level: 1,
      },
      {
        id: 'binding_judgment',
        name: 'Binding Judgment',
        element: 'Order',
        icon: '📜',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Judicial seal locking movement.',
        level: 1,
      },
      {
        id: 'aura_of_truth',
        name: 'Aura of Truth',
        element: 'Order',
        icon: '✨',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Dispels chaos in an area.',
        level: 1,
      },
      {
        id: 'invariable_edict',
        name: 'Invariable Edict',
        element: 'Order',
        icon: '⚖️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Enforces immutable mathematical law.',
        level: 1,
      },
    ],
  },

  Matter: {
    element: 'Matter',
    className: 'Mattershaper',
    avatar: '🧱',
    title: 'Master of Atomic Density',
    tagline: 'Shape solid matter into obstacles and barriers.',
    description: 'High defense and solid barriers.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'matter_crush',
        name: 'Matter Crush',
        element: 'Matter',
        icon: '🧱',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 18,
        description: 'Dense matter punch.',
        level: 1,
      },
      {
        id: 'density_spike',
        name: 'Density Spike',
        element: 'Matter',
        icon: '🧱',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Spike of hyper-dense atoms.',
        level: 1,
      },
      {
        id: 'barrier_wall',
        name: 'Barrier Wall',
        element: 'Matter',
        icon: '🛡️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 35,
        description: 'Constructs temporary barrier wall.',
        level: 1,
      },
      {
        id: 'atomic_collapse',
        name: 'Atomic Collapse',
        element: 'Matter',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Collapses atomic structure into crushing explosion.',
        level: 1,
      },
    ],
  },

  Gravity: {
    element: 'Gravity',
    className: 'Gravimancer',
    avatar: '🪐',
    title: 'Master of Gravitational Pull',
    tagline: 'Increase target weight and pull foes into crushing singularities.',
    description: 'Area gravity wells pulling enemies.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'gravity_slam',
        name: 'Gravity Slam',
        element: 'Gravity',
        icon: '🪐',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        description: 'Quadruples gravity under target.',
        level: 1,
      },
      {
        id: 'gravitational_well',
        name: 'Gravitational Well',
        element: 'Gravity',
        icon: '🌀',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Pulls target toward focal point.',
        level: 1,
      },
      {
        id: 'crushing_horizon',
        name: 'Crushing Horizon',
        element: 'Gravity',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 37,
        description: 'Area gravity crush.',
        level: 1,
      },
      {
        id: 'hyper_singularity',
        name: 'Hyper Singularity',
        element: 'Gravity',
        icon: '🪐',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        description: 'Micro black hole gravity well.',
        level: 1,
      },
    ],
  },

  Momentum: {
    element: 'Momentum',
    className: 'Speedster',
    avatar: '⏩',
    title: 'Master of Kinetic Velocity',
    tagline: 'Multiply damage per tile traveled.',
    description: 'High AP efficiency and movement scaling.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'momentum_jab',
        name: 'Momentum Jab',
        element: 'Momentum',
        icon: '⏩',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        description: 'Fast strike with speed momentum.',
        level: 1,
      },
      {
        id: 'sonic_dash',
        name: 'Sonic Dash',
        element: 'Momentum',
        icon: '🏃',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        description: 'Dashes through enemy with speed.',
        level: 1,
      },
      {
        id: 'kinetic_barrage',
        name: 'Kinetic Barrage',
        element: 'Momentum',
        icon: '💨',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 35,
        description: 'Hundred-strike supersonic flurry.',
        level: 1,
      },
      {
        id: 'infinite_velocity',
        name: 'Infinite Velocity',
        element: 'Momentum',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 44,
        description: 'Relativistic speed collision.',
        level: 1,
      },
    ],
  },

  Vibration: {
    element: 'Vibration',
    className: 'Seismomancer',
    avatar: '〰️',
    title: 'Master of Resonant Frequency',
    tagline: 'Vibrate target molecules to shatter physical integrity.',
    description: 'Armor shattering and seismic tremors.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'vibrating_strike',
        name: 'Vibrating Strike',
        element: 'Vibration',
        icon: '〰️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        description: 'High-frequency strike.',
        level: 1,
      },
      {
        id: 'seismic_tremor',
        name: 'Seismic Tremor',
        element: 'Vibration',
        icon: '💥',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Earth-shaking vibration pulse.',
        level: 1,
      },
      {
        id: 'resonance_rupture',
        name: 'Resonance Rupture',
        element: 'Vibration',
        icon: '〰️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Ruptures enemy armor via resonant vibration.',
        level: 1,
      },
      {
        id: 'tectonic_resonance',
        name: 'Tectonic Resonance',
        element: 'Vibration',
        icon: '🌋',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Cataclysmic seismic frequency wave.',
        level: 1,
      },
    ],
  },

  Radiation: {
    element: 'Radiation',
    className: 'Radionecrotic',
    avatar: '☢️',
    title: 'Master of Ionizing Decay',
    tagline: 'Contaminate targets with irreversible cell decay.',
    description: 'Irreversible stat reductions and gamma bursts.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'rad_dart',
        name: 'Radiation Dart',
        element: 'Radiation',
        icon: '☢️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        description: 'Emits radioactive particle burst.',
        level: 1,
      },
      {
        id: 'gamma_ray',
        name: 'Gamma Ray',
        element: 'Radiation',
        icon: '⚡',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 27,
        description: 'High-energy gamma photon beam.',
        level: 1,
      },
      {
        id: 'meltdown_field',
        name: 'Meltdown Field',
        element: 'Radiation',
        icon: '☣️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 37,
        createsHazard: 'ToxicMire',
        hazardDuration: 3,
        description: 'Contaminates battlefield with radioactive fallout.',
        level: 1,
      },
      {
        id: 'critical_mass',
        name: 'Critical Mass',
        element: 'Radiation',
        icon: '☢️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        description: 'Nuclear chain reaction detonation.',
        level: 1,
      },
    ],
  },

  Pressure: {
    element: 'Pressure',
    className: 'Baromancer',
    avatar: '🔽',
    title: 'Master of Atmospheric Compression',
    tagline: 'Crush targets under thousands of atmospheres.',
    description: 'Compressive crushing and barometric shocks.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'pressure_blast',
        name: 'Pressure Blast',
        element: 'Pressure',
        icon: '🔽',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        description: 'Sudden pressure drop concussing foe.',
        level: 1,
      },
      {
        id: 'crushing_depths',
        name: 'Crushing Depths',
        element: 'Pressure',
        icon: '🌊',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        description: 'Simulates abyssal trench pressure.',
        level: 1,
      },
      {
        id: 'barometric_implosion',
        name: 'Barometric Implosion',
        element: 'Pressure',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Implodes target area with high barometric differential.',
        level: 1,
      },
      {
        id: 'hyperbaric_crush',
        name: 'Hyperbaric Crush',
        element: 'Pressure',
        icon: '🔽',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Crushes target completely into fine dust.',
        level: 1,
      },
    ],
  },

  Heat: {
    element: 'Heat',
    className: 'Thermomancer',
    avatar: '♨️',
    title: 'Master of Thermal Energy',
    tagline: 'Raise target temperature until spontaneous ignition.',
    description: 'Thermal expansion and melting.',
    category: 'Primal',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'thermal_scorch',
        name: 'Thermal Scorch',
        element: 'Heat',
        icon: '♨️',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 16,
        appliesStatus: 'Burning',
        statusDuration: 2,
        description: 'Superheats target surface.',
        level: 1,
      },
      {
        id: 'heat_wave',
        name: 'Heat Wave',
        element: 'Heat',
        icon: '🔥',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 25,
        description: 'Scorching thermal wave.',
        level: 1,
      },
      {
        id: 'thermal_overload',
        name: 'Thermal Overload',
        element: 'Heat',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        appliesStatus: 'Burning',
        statusDuration: 3,
        description: 'Overheats area causing spontaneous combustion.',
        level: 1,
      },
      {
        id: 'plasma_sun',
        name: 'Plasma Sun',
        element: 'Heat',
        icon: '☀️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Creates temporary solar core.',
        level: 1,
      },
    ],
  },

  Cold: {
    element: 'Cold',
    className: 'Frost Adept',
    avatar: '🥶',
    title: 'Master of Sub-Zero Entropy',
    tagline: 'Slow molecular movement and drain kinetic warmth.',
    description: 'Chilling slow and frost buildup.',
    category: 'Primal',
    unlockRequirement: 'Defeat Round 5 Boss',
    abilities: [
      {
        id: 'chill_touch',
        name: 'Chill Touch',
        element: 'Cold',
        icon: '🥶',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 15,
        description: 'Numbing sub-zero touch.',
        level: 1,
      },
      {
        id: 'blizzard_blast',
        name: 'Blizzard Blast',
        element: 'Cold',
        icon: '❄️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        appliesStatus: 'Frozen',
        statusDuration: 2,
        description: 'Blizzard gale chilling targets.',
        level: 1,
      },
      {
        id: 'permafrost_freeze',
        name: 'Permafrost Freeze',
        element: 'Cold',
        icon: '🧊',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 35,
        appliesStatus: 'Frozen',
        statusDuration: 2,
        description: 'Encases area in eternal permafrost.',
        level: 1,
      },
      {
        id: 'glacial_extinction',
        name: 'Glacial Extinction',
        element: 'Cold',
        icon: '❄️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 44,
        description: 'Instant ice age flash-freeze.',
        level: 1,
      },
    ],
  },

  Glass: {
    element: 'Glass',
    className: 'Vitreomancer',
    avatar: '🪟',
    title: 'Master of Razor Reflection',
    tagline: 'Reflect projectiles and slice with microscopic glass blades.',
    description: 'Reflective razor surfaces and bleeding cuts.',
    category: 'Forces',
    unlockRequirement: 'Defeat Round 10 Boss',
    abilities: [
      {
        id: 'glass_shard',
        name: 'Glass Shard',
        element: 'Glass',
        icon: '🪟',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        appliesStatus: 'Bleeding',
        statusDuration: 2,
        description: 'Hurls razor-sharp glass shard.',
        level: 1,
      },
      {
        id: 'mirror_shield',
        name: 'Mirror Shield',
        element: 'Glass',
        icon: '🪞',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 3,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 24,
        appliesStatus: 'Shielded',
        statusDuration: 2,
        description: 'Reflective mirror reflecting projectiles.',
        level: 1,
      },
      {
        id: 'shattered_glass_storm',
        name: 'Shattered Glass Storm',
        element: 'Glass',
        icon: '🌪️',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        description: 'Whirling vortex of razor glass.',
        level: 1,
      },
      {
        id: 'prismatic_fracture',
        name: 'Prismatic Fracture',
        element: 'Glass',
        icon: '💎',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 45,
        description: 'Fractures reality into million glass shards.',
        level: 1,
      },
    ],
  },

  Undead: {
    element: 'Undead',
    className: 'Necromancer',
    avatar: '🧟‍♂️',
    title: 'Master of the Restless Tomb',
    tagline: 'Summon necrotic plague, siphon life force, and command the army of the dead.',
    description: 'Specializes in lifesteal, necrotic rot, and persistent undead curses.',
    category: 'Cosmic',
    unlockRequirement: '👑 Admin Exclusive (Unobtainable by Players)',
    abilities: [
      {
        id: 'grave_strike',
        name: 'Grave Strike',
        element: 'Undead',
        icon: '🦴',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 2,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 17,
        description: 'Strikes with cold bony hand dealing necrotic damage.',
        level: 1,
      },
      {
        id: 'necrotic_plague',
        name: 'Necrotic Plague',
        element: 'Undead',
        icon: '🧟‍♂️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 26,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        description: 'Infects target with incurable creeping necrosis.',
        level: 1,
      },
      {
        id: 'corpse_explosion',
        name: 'Corpse Explosion',
        element: 'Undead',
        icon: '💥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 37,
        description: 'Detonates necrotic bone fragments across an area.',
        level: 1,
      },
      {
        id: 'army_of_the_dead',
        name: 'Army of the Dead',
        element: 'Undead',
        icon: '💀',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 46,
        appliesStatus: 'VoidMarked',
        statusDuration: 2,
        description: 'Unleashes a tidal swarm of undead ghouls.',
        level: 1,
      },
      {
        id: 'raise_undead_horde',
        name: 'Raise Undead Horde',
        element: 'Undead',
        icon: '⚰️',
        apCost: 3,
        cooldown: 2,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 1,
        targeting: 'Self',
        baseDamage: 0,
        description: 'Raises 4 reanimated zombies from the ground in free tiles adjacent to the Necromancer.',
        level: 1,
      },
    ],
  },

  Neutral: {
    element: 'Neutral',
    className: 'Omnipotent Avatar',
    avatar: '👑✨',
    title: 'Master of All 42 Elements',
    tagline: 'Wield the omnipotent arsenal of every elemental domain.',
    description: 'Supreme elemental conduit possessing devastating powers from all 42 elements simultaneously.',
    category: 'Cosmic',
    isStarter: true,
    bonusStats: {
      maxHp: 150,
      maxAp: 8,
    },
    abilities: [
      {
        id: 'avatar_inferno',
        name: 'Inferno Supernova',
        element: 'Fire',
        icon: '🔥',
        apCost: 1,
        cooldown: 0,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 0,
        targeting: 'SingleUnit',
        baseDamage: 32,
        appliesStatus: 'Burning',
        statusDuration: 3,
        description: 'Strikes foe with blazing cosmic plasma flame.',
        level: 1,
      },
      {
        id: 'avatar_lightning',
        name: 'Chain Overload',
        element: 'Lightning',
        icon: '⚡',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 40,
        description: 'Blasts area with high-voltage chain lightning.',
        level: 1,
      },
      {
        id: 'avatar_raise_horde',
        name: 'Raise Undead Horde',
        element: 'Undead',
        icon: '⚰️',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 1,
        aoeRadius: 1,
        targeting: 'Self',
        baseDamage: 0,
        description: 'Raises 4 reanimated zombies from the ground in free adjacent tiles.',
        level: 1,
      },
      {
        id: 'avatar_unzombify',
        name: 'Unzombify Explosion',
        element: 'Life',
        icon: '🧚',
        apCost: 2,
        cooldown: 0,
        currentCooldown: 0,
        range: 6,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 48,
        description: 'Unzombifies zombies in 3x3 AoE causing cascading explosions and spawns a Being of Life.',
        level: 1,
      },
      {
        id: 'avatar_void_collapse',
        name: 'Void Singularity',
        element: 'Void',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 6,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 65,
        appliesStatus: 'VoidMarked',
        statusDuration: 3,
        description: 'Opens a gravitational singularity dealing colossal cosmic void damage.',
        level: 1,
      },
    ],
  },
};

export function createHeroForElement(element: ElementType): Unit {
  const config = HERO_CLASSES[element] || HERO_CLASSES.Fire;
  const maxHp = config.bonusStats?.maxHp || 100;
  const maxAp = config.bonusStats?.maxAp || 6;

  // Deep copy abilities to prevent state bleed
  const abilities: Ability[] = config.abilities.map((ab) => ({
    ...ab,
    currentCooldown: 0,
  }));

  return {
    id: 'hero',
    name: config.className,
    faction: 'Player',
    avatar: config.avatar,
    coord: { x: 1, y: 1 },
    stats: {
      maxHp,
      currentHp: maxHp,
      maxAp,
      currentAp: maxAp,
      moveCostPerTile: 1,
      elementalAffinity: config.element,
    },
    abilities,
    statusEffects: [],
    isDead: false,
  };
}
