// Elemental Mayhem - Complete 42 Elements Registry & Dynamic Interaction Matrix
import { ElementData, ElementType } from '../types';

export const CORE_ELEMENTS: Record<ElementType, ElementData> = {
  // Primal Elements
  Fire: {
    id: 'Fire',
    name: 'Fire',
    color: '#ff6b35',
    glowColor: 'rgba(255, 107, 53, 0.5)',
    icon: '🔥',
    category: 'Primal',
    description: 'Blazing destructive power causing continuous burning and explosive volatile reactions.',
    strongAgainst: ['Poison', 'Earth', 'Ice', 'Nature', 'Metal'],
    weakAgainst: ['Water', 'Void', 'Acid'],
  },
  Water: {
    id: 'Water',
    name: 'Water',
    color: '#00d2ff',
    glowColor: 'rgba(0, 210, 255, 0.5)',
    icon: '💧',
    category: 'Primal',
    description: 'Fluid conductive force soaking targets and spreading lightning conductivity.',
    strongAgainst: ['Fire', 'Earth', 'Magma'],
    weakAgainst: ['Lightning', 'Poison', 'Ice'],
  },
  Lightning: {
    id: 'Lightning',
    name: 'Lightning',
    color: '#ffd000',
    glowColor: 'rgba(255, 208, 0, 0.5)',
    icon: '⚡',
    category: 'Forces',
    description: 'Instantaneous ionization shocking enemies and reducing Action Points.',
    strongAgainst: ['Water', 'Void', 'Metal', 'Sky'],
    weakAgainst: ['Earth', 'Crystal'],
  },
  Earth: {
    id: 'Earth',
    name: 'Earth',
    color: '#ca8a04',
    glowColor: 'rgba(202, 138, 4, 0.5)',
    icon: '🪨',
    category: 'Primal',
    description: 'Solid mineral fortitude grounding electricity and raising defensive stone obstacles.',
    strongAgainst: ['Lightning', 'Fire', 'Wind', 'Electricity'],
    weakAgainst: ['Water', 'Poison', 'Nature'],
  },
  Poison: {
    id: 'Poison',
    name: 'Poison',
    color: '#22c55e',
    glowColor: 'rgba(34, 197, 94, 0.5)',
    icon: '🧪',
    category: 'Life',
    description: 'Corrosive venom stacking damage over time and exploding violently when ignited.',
    strongAgainst: ['Water', 'Earth', 'Life', 'Nature'],
    weakAgainst: ['Fire', 'Void', 'Metal'],
  },
  Void: {
    id: 'Void',
    name: 'Void',
    color: '#d946ef',
    glowColor: 'rgba(217, 70, 239, 0.5)',
    icon: '🌌',
    category: 'Cosmic',
    description: 'Entropic cosmic darkness pulling targets and collapsing status effects.',
    strongAgainst: ['Fire', 'Poison', 'Light', 'Space'],
    weakAgainst: ['Lightning', 'Chaos'],
  },

  // Requested Elements Expansion
  Love: {
    id: 'Love',
    name: 'Love',
    color: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.5)',
    icon: '💖',
    category: 'Life',
    description: 'Empathetic affection charming foes, converting damage to vitality, and soothing allies.',
    strongAgainst: ['Darkness', 'Death', 'Chaos'],
    weakAgainst: ['Void', 'Acid'],
  },
  Sky: {
    id: 'Sky',
    name: 'Sky',
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.5)',
    icon: '☁️',
    category: 'Primal',
    description: 'Vast atmospheric winds lifting combatants, enhancing mobility, and clearing ground hazards.',
    strongAgainst: ['Earth', 'Nature', 'Poison'],
    weakAgainst: ['Lightning', 'Storm'],
  },
  Nature: {
    id: 'Nature',
    name: 'Nature',
    color: '#16a34a',
    glowColor: 'rgba(22, 163, 74, 0.5)',
    icon: '🌿',
    category: 'Life',
    description: 'Flourishing vitality and thorny flora rooting enemies and siphoning biological essence.',
    strongAgainst: ['Water', 'Earth', 'Crystal'],
    weakAgainst: ['Fire', 'Ice', 'Acid'],
  },
  Ice: {
    id: 'Ice',
    name: 'Ice',
    color: '#93c5fd',
    glowColor: 'rgba(147, 197, 253, 0.5)',
    icon: '❄️',
    category: 'Primal',
    description: 'Sub-zero temperatures freezing wet targets solid, shattering armor, and creating slick surfaces.',
    strongAgainst: ['Water', 'Nature', 'Wind'],
    weakAgainst: ['Fire', 'Magma', 'Metal'],
  },
  Metal: {
    id: 'Metal',
    name: 'Metal',
    color: '#94a3b8',
    glowColor: 'rgba(148, 163, 184, 0.5)',
    icon: '🛡️',
    category: 'Forces',
    description: 'Heavy metallurgical density offering impenetrable shielding and magnetic resonance.',
    strongAgainst: ['Ice', 'Earth', 'Crystal'],
    weakAgainst: ['Fire', 'Lightning', 'Acid'],
  },
  Darkness: {
    id: 'Darkness',
    name: 'Darkness',
    color: '#6b21a8',
    glowColor: 'rgba(107, 33, 168, 0.5)',
    icon: '🌑',
    category: 'Cosmic',
    description: 'Umbral shadows obscuring vision, draining life essence, and triggering nightfall burst.',
    strongAgainst: ['Light', 'Soul', 'Spirit'],
    weakAgainst: ['Light', 'Love'],
  },
  Light: {
    id: 'Light',
    name: 'Light',
    color: '#fef08a',
    glowColor: 'rgba(254, 240, 138, 0.5)',
    icon: '☀️',
    category: 'Cosmic',
    description: 'Radiant illumination purging dark anomalies and blinding enemies with solar brilliance.',
    strongAgainst: ['Darkness', 'Death', 'Blood', 'Soul'],
    weakAgainst: ['Void', 'Chaos'],
  },
  Electricity: {
    id: 'Electricity',
    name: 'Electricity',
    color: '#facc15',
    glowColor: 'rgba(250, 204, 21, 0.5)',
    icon: '⚡',
    category: 'Forces',
    description: 'Raw electric current shocking and chaining continuous voltage across targets.',
    strongAgainst: ['Water', 'Metal'],
    weakAgainst: ['Earth', 'Glass'],
  },
  Sound: {
    id: 'Sound',
    name: 'Sound',
    color: '#06b6d4',
    glowColor: 'rgba(6, 182, 212, 0.5)',
    icon: '🔊',
    category: 'Forces',
    description: 'Acoustic shockwaves shattering physical structures and stunning enemy turns.',
    strongAgainst: ['Crystal', 'Glass', 'Metal'],
    weakAgainst: ['Void', 'Space'],
  },
  Time: {
    id: 'Time',
    name: 'Time',
    color: '#eab308',
    glowColor: 'rgba(234, 179, 8, 0.5)',
    icon: '⏳',
    category: 'Cosmic',
    description: 'Temporal distortion bending turns, accelerating cooldowns, and aging enemy stats.',
    strongAgainst: ['Space', 'Death', 'Life'],
    weakAgainst: ['Chaos', 'Void'],
  },
  Death: {
    id: 'Death',
    name: 'Death',
    color: '#475569',
    glowColor: 'rgba(71, 85, 105, 0.5)',
    icon: '💀',
    category: 'Cosmic',
    description: 'Necrotic decay reaping souls, detonating corpses, and executing low-health targets.',
    strongAgainst: ['Life', 'Nature', 'Blood'],
    weakAgainst: ['Life', 'Light', 'Love'],
  },
  Life: {
    id: 'Life',
    name: 'Life',
    color: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.5)',
    icon: '🌱',
    category: 'Life',
    description: 'Primal biological resurgence providing sustained regeneration and radiant rejuvenation.',
    strongAgainst: ['Death', 'Darkness', 'Void'],
    weakAgainst: ['Death', 'Poison', 'Acid'],
  },
  Chaos: {
    id: 'Chaos',
    name: 'Chaos',
    color: '#ec4899',
    glowColor: 'rgba(236, 72, 153, 0.5)',
    icon: '🌀',
    category: 'Cosmic',
    description: 'Unpredictable entropic madness unleashing randomized elemental cascades.',
    strongAgainst: ['Order', 'Time', 'Light'],
    weakAgainst: ['Order', 'Force'],
  },
  Order: {
    id: 'Order',
    name: 'Order',
    color: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.5)',
    icon: '⚖️',
    category: 'Cosmic',
    description: 'Immutable law nullifying randomness, dispelling status anomalies, and securing precision.',
    strongAgainst: ['Chaos', 'Darkness'],
    weakAgainst: ['Chaos', 'Void'],
  },
  Acid: {
    id: 'Acid',
    name: 'Acid',
    color: '#84cc16',
    glowColor: 'rgba(132, 204, 22, 0.5)',
    icon: '🧪',
    category: 'Life',
    description: 'Caustic chemical breakdown dissolving metallic armor and creating hazardous acid pools.',
    strongAgainst: ['Metal', 'Earth', 'Crystal'],
    weakAgainst: ['Water', 'Life'],
  },
  Blood: {
    id: 'Blood',
    name: 'Blood',
    color: '#dc2626',
    glowColor: 'rgba(220, 38, 38, 0.5)',
    icon: '🩸',
    category: 'Life',
    description: 'Hemomantic siphon inflicting persistent bleeding and powering devastating blood bursts.',
    strongAgainst: ['Life', 'Soul', 'Spirit'],
    weakAgainst: ['Light', 'Fire'],
  },
  Soul: {
    id: 'Soul',
    name: 'Soul',
    color: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    icon: '👻',
    category: 'Cosmic',
    description: 'Ethereal consciousness piercing physical defenses and binding target spirits.',
    strongAgainst: ['Death', 'Darkness', 'Matter'],
    weakAgainst: ['Light', 'Spirit'],
  },
  Spirit: {
    id: 'Spirit',
    name: 'Spirit',
    color: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.5)',
    icon: '✨',
    category: 'Cosmic',
    description: 'Ancestral guardian essence providing spectral shields and transcendent bursts.',
    strongAgainst: ['Soul', 'Void'],
    weakAgainst: ['Darkness', 'Blood'],
  },
  Energy: {
    id: 'Energy',
    name: 'Energy',
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.5)',
    icon: '⚡',
    category: 'Forces',
    description: 'Pure kinetic and electromagnetic plasma unleashing overwhelming damage beam lines.',
    strongAgainst: ['Matter', 'Force'],
    weakAgainst: ['Void', 'Earth'],
  },
  Force: {
    id: 'Force',
    name: 'Force',
    color: '#f97316',
    glowColor: 'rgba(249, 115, 22, 0.5)',
    icon: '💥',
    category: 'Forces',
    description: 'Raw physical momentum pushing enemies into walls and hazards with crushing impact.',
    strongAgainst: ['Metal', 'Earth', 'Crystal'],
    weakAgainst: ['Space', 'Void'],
  },
  Matter: {
    id: 'Matter',
    name: 'Matter',
    color: '#78716c',
    glowColor: 'rgba(120, 113, 108, 0.5)',
    icon: '🧱',
    category: 'Forces',
    description: 'Dense physical substance creating tangible barriers and crushing bludgeons.',
    strongAgainst: ['Energy', 'Light'],
    weakAgainst: ['Chaos', 'Void'],
  },
  Space: {
    id: 'Space',
    name: 'Space',
    color: '#6366f1',
    glowColor: 'rgba(99, 102, 241, 0.5)',
    icon: '🌌',
    category: 'Cosmic',
    description: 'Spatial fabric manipulation bending battlefield coordinates and opening warp rifts.',
    strongAgainst: ['Matter', 'Force'],
    weakAgainst: ['Time', 'Gravity'],
  },
  Gravity: {
    id: 'Gravity',
    name: 'Gravity',
    color: '#4338ca',
    glowColor: 'rgba(67, 56, 202, 0.5)',
    icon: '🪐',
    category: 'Forces',
    description: 'Gravitational acceleration pulling all foes into focal points and increasing move costs.',
    strongAgainst: ['Space', 'Sky', 'Wind'],
    weakAgainst: ['Energy', 'Sound'],
  },
  Momentum: {
    id: 'Momentum',
    name: 'Momentum',
    color: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.5)',
    icon: '⏩',
    category: 'Forces',
    description: 'Kinetic acceleration multiplying damage and AP refund per tile traveled.',
    strongAgainst: ['Earth', 'Metal'],
    weakAgainst: ['Earth', 'Ice'],
  },
  Vibration: {
    id: 'Vibration',
    name: 'Vibration',
    color: '#14b8a6',
    glowColor: 'rgba(20, 184, 166, 0.5)',
    icon: '〰️',
    category: 'Forces',
    description: 'Oscillatory frequency disintegrating armor and triggering seismic tremors.',
    strongAgainst: ['Crystal', 'Glass', 'Earth'],
    weakAgainst: ['Void', 'Water'],
  },
  Radiation: {
    id: 'Radiation',
    name: 'Radiation',
    color: '#84cc16',
    glowColor: 'rgba(132, 204, 22, 0.5)',
    icon: '☢️',
    category: 'Forces',
    description: 'Ionizing decay contaminating target cells with permanent stat degradation.',
    strongAgainst: ['Life', 'Nature', 'Water'],
    weakAgainst: ['Metal', 'Earth'],
  },
  Magnetism: {
    id: 'Magnetism',
    name: 'Magnetism',
    color: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.5)',
    icon: '🧲',
    category: 'Forces',
    description: 'Bipolar magnetic forces polarizing units to attract or violently repel each other.',
    strongAgainst: ['Metal', 'Electricity'],
    weakAgainst: ['Earth', 'Glass'],
  },
  Pressure: {
    id: 'Pressure',
    name: 'Pressure',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.5)',
    icon: '🔽',
    category: 'Forces',
    description: 'Barometric and hydraulic compression crushing enemies under atmospheres of force.',
    strongAgainst: ['Sky', 'Wind'],
    weakAgainst: ['Space', 'Void'],
  },
  Heat: {
    id: 'Heat',
    name: 'Heat',
    color: '#ea580c',
    glowColor: 'rgba(234, 88, 12, 0.5)',
    icon: '♨️',
    category: 'Primal',
    description: 'Thermal expansion elevating target temperatures into molten combustion.',
    strongAgainst: ['Cold', 'Ice'],
    weakAgainst: ['Water', 'Void'],
  },
  Cold: {
    id: 'Cold',
    name: 'Cold',
    color: '#67e8f9',
    glowColor: 'rgba(103, 232, 249, 0.5)',
    icon: '🥶',
    category: 'Primal',
    description: 'Kinetic entropy freezing molecular bonds and slowing actions.',
    strongAgainst: ['Heat', 'Fire'],
    weakAgainst: ['Magma', 'Light'],
  },
  Wind: {
    id: 'Wind',
    name: 'Wind',
    color: '#2dd4bf',
    glowColor: 'rgba(45, 212, 191, 0.5)',
    icon: '💨',
    category: 'Primal',
    description: 'Swift aerial slicing slicing through defenses with pinpoint aerodynamic speed.',
    strongAgainst: ['Earth', 'Poison'],
    weakAgainst: ['Fire', 'Ice'],
  },
  Storm: {
    id: 'Storm',
    name: 'Storm',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.5)',
    icon: '⛈️',
    category: 'Forces',
    description: 'Violent tempest combining deluge and lightning into devastating tempest storms.',
    strongAgainst: ['Fire', 'Earth', 'Sky'],
    weakAgainst: ['Earth', 'Void'],
  },
  Thunder: {
    id: 'Thunder',
    name: 'Thunder',
    color: '#facc15',
    glowColor: 'rgba(250, 204, 21, 0.5)',
    icon: '⚡',
    category: 'Forces',
    description: 'Sonic boom following lightning that dazes, deafens, and knocks foes back.',
    strongAgainst: ['Water', 'Sky', 'Crystal'],
    weakAgainst: ['Earth', 'Void'],
  },
  Magma: {
    id: 'Magma',
    name: 'Magma',
    color: '#dc2626',
    glowColor: 'rgba(220, 38, 38, 0.5)',
    icon: '🌋',
    category: 'Primal',
    description: 'Molten liquid rock engulfing the arena in inescapable flaming lava pools.',
    strongAgainst: ['Ice', 'Nature', 'Metal'],
    weakAgainst: ['Water', 'Void'],
  },
  Glass: {
    id: 'Glass',
    name: 'Glass',
    color: '#e0e7ff',
    glowColor: 'rgba(224, 231, 255, 0.5)',
    icon: '🪟',
    category: 'Forces',
    description: 'Reflective razor surfaces refracting beams and reflecting projectile spells.',
    strongAgainst: ['Light', 'Energy'],
    weakAgainst: ['Sound', 'Force', 'Metal'],
  },
  Crystal: {
    id: 'Crystal',
    name: 'Crystal',
    color: '#a855f7',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    icon: '💎',
    category: 'Primal',
    description: 'Resonant geometric prisms amplifying magical spells and piercing armor.',
    strongAgainst: ['Light', 'Darkness', 'Energy'],
    weakAgainst: ['Sound', 'Metal', 'Earth'],
  },
  Undead: {
    id: 'Undead',
    name: 'Undead',
    color: '#84cc16',
    glowColor: 'rgba(132, 204, 22, 0.5)',
    icon: '🧟‍♂️',
    category: 'Cosmic',
    description: 'Relentless necrotic power raising skeletal thralls, siphoning lifeforce, and defying mortal death.',
    strongAgainst: ['Poison', 'Blood', 'Death'],
    weakAgainst: ['Light', 'Life', 'Fire'],
  },
  Neutral: {
    id: 'Neutral',
    name: 'Neutral',
    color: '#94a3b8',
    glowColor: 'rgba(148, 163, 184, 0.3)',
    icon: '⚔️',
    category: 'Primal',
    description: 'Basic physical force without elemental affinity.',
    strongAgainst: [],
    weakAgainst: [],
  },
};

// Complete 42 Elements Registry from elements.md for game lore & expansion
export const ALL_42_ELEMENTS = [
  'Sky', 'Love', 'Fire', 'Nature', 'Water', 'Ice', 'Metal', 'Darkness', 'Light',
  'Electricity', 'Sound', 'Time', 'Death', 'Life', 'Void', 'Chaos', 'Order',
  'Poison', 'Acid', 'Blood', 'Soul', 'Spirit', 'Energy', 'Force', 'Matter',
  'Space', 'Gravity', 'Momentum', 'Vibration', 'Radiation', 'Magnetism', 'Pressure',
  'Heat', 'Cold', 'Wind', 'Storm', 'Lightning', 'Thunder', 'Earth', 'Magma',
  'Glass', 'Crystal'
] as const;

export const DEFAULT_GRID_SIZE = 10;
export const DEFAULT_HERO_HP = 100;
export const DEFAULT_HERO_AP = 6;
export const DEFAULT_MOVE_COST = 1; // 1 AP per tile
