// Elemental Mayhem - Multi-Tier Escalation & Boss Gauntlet Engine
import { Unit, Ability, PassiveRelic, ElementType } from '../types';
import { upgradeToCPUChampion } from '../constants/classes';

export class EscalationManager {
  public generateRoundEnemies(round: number): Unit[] {
    const enemies: Unit[] = [];

    switch (round) {
      case 1:
        // Round 1: Toxic Mire Adept + Earth Sentinel
        enemies.push({
          id: 'enemy_r1_1',
          name: 'Toxic Mire Adept',
          faction: 'Enemy',
          avatar: '🧪',
          coord: { x: 8, y: 3 },
          stats: {
            maxHp: 45,
            currentHp: 45,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Poison',
          },
          abilities: [
            {
              id: 'venom_spit',
              name: 'Venom Spit',
              element: 'Poison',
              icon: '🧪',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 16,
              appliesStatus: 'Poisoned',
              statusDuration: 3,
              createsHazard: 'ToxicMire',
              hazardDuration: 2,
              description: 'Spits corrosive venom.',
              level: 1,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r1_2',
          name: 'Earth Sentinel',
          faction: 'Enemy',
          avatar: '🪨',
          coord: { x: 7, y: 7 },
          stats: {
            maxHp: 55,
            currentHp: 55,
            maxAp: 3,
            currentAp: 3,
            moveCostPerTile: 1,
            elementalAffinity: 'Earth',
          },
          abilities: [
            {
              id: 'stone_strike',
              name: 'Stone Strike',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 2,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 20,
              description: 'Strikes with hardened earth.',
              level: 1,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 2:
        // Round 2: Pyroclast Sorcerer + Hydrokinetic Monk + Storm Invoker
        enemies.push({
          id: 'enemy_r2_1',
          name: 'Pyroclast Sorcerer',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 60,
            currentHp: 60,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'combustion_beam',
              name: 'Combustion Beam',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 22,
              appliesStatus: 'Burning',
              statusDuration: 3,
              createsHazard: 'Burning',
              hazardDuration: 2,
              description: 'Lethal beam of flame.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r2_2',
          name: 'Hydrokinetic Monk',
          faction: 'Enemy',
          avatar: '💧',
          coord: { x: 7, y: 5 },
          stats: {
            maxHp: 55,
            currentHp: 55,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Water',
          },
          abilities: [
            {
              id: 'tidal_surge',
              name: 'Tidal Surge',
              element: 'Water',
              icon: '💧',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 20,
              appliesStatus: 'Wet',
              statusDuration: 3,
              createsHazard: 'Puddle',
              hazardDuration: 3,
              description: 'Surging wave of pressurized water.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r2_3',
          name: 'Storm Invoker',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 8, y: 8 },
          stats: {
            maxHp: 50,
            currentHp: 50,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'arc_discharge',
              name: 'Arc Discharge',
              element: 'Lightning',
              icon: '⚡',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 28,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Discharges chaining lightning.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 3:
        // Round 3: Venom Spitter + Spark Weaver + Magma Brute
        enemies.push({
          id: 'enemy_r3_1',
          name: 'Venom Spitter',
          faction: 'Enemy',
          avatar: '🐍',
          coord: { x: 8, y: 1 },
          stats: {
            maxHp: 65,
            currentHp: 65,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Poison',
          },
          abilities: [
            {
              id: 'venom_dart',
              name: 'Venom Dart',
              element: 'Poison',
              icon: '🧪',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 24,
              appliesStatus: 'Poisoned',
              statusDuration: 3,
              description: 'Dart soaked in deadly poison.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r3_2',
          name: 'Magma Brute',
          faction: 'Enemy',
          avatar: '🌋',
          coord: { x: 6, y: 4 },
          stats: {
            maxHp: 80,
            currentHp: 80,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'magma_slam',
              name: 'Magma Slam',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 2,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 26,
              createsHazard: 'Burning',
              hazardDuration: 2,
              description: 'Slams ground with molten fury.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r3_3',
          name: 'Spark Weaver',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 8, y: 7 },
          stats: {
            maxHp: 60,
            currentHp: 60,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'volt_lance',
              name: 'Volt Lance',
              element: 'Lightning',
              icon: '⚡',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 26,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Pinpoint javelin of lightning.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 4:
        // Round 4: Nether Witch + Blazing Berserker + Granite Golem
        enemies.push({
          id: 'enemy_r4_1',
          name: 'Nether Witch',
          faction: 'Enemy',
          avatar: '🧙‍♀️',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 75,
            currentHp: 75,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'void_curse',
              name: 'Void Curse',
              element: 'Void',
              icon: '🌌',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 28,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Marks target with entropic decay.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r4_2',
          name: 'Blazing Berserker',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 6, y: 5 },
          stats: {
            maxHp: 85,
            currentHp: 85,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'flame_cleave',
              name: 'Flame Cleave',
              element: 'Fire',
              icon: '⚔️',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 2,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 30,
              createsHazard: 'Burning',
              hazardDuration: 2,
              description: 'Sweeping fiery blade strike.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r4_3',
          name: 'Granite Golem',
          faction: 'Enemy',
          avatar: '🗿',
          coord: { x: 7, y: 8 },
          stats: {
            maxHp: 95,
            currentHp: 95,
            maxAp: 3,
            currentAp: 3,
            moveCostPerTile: 1,
            elementalAffinity: 'Earth',
          },
          abilities: [
            {
              id: 'earth_boulder',
              name: 'Earth Boulder',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 32,
              appliesStatus: 'Rooted',
              statusDuration: 2,
              description: 'Hurls massive boulder.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 5:
        // 👑 BOSS 1 (Round 5): IGNIS COLOSSUS + 2x Flame Wisps
        enemies.push({
          id: 'boss_ignis_colossus',
          name: 'IGNIS COLOSSUS (Boss)',
          faction: 'Enemy',
          avatar: '👑',
          coord: { x: 8, y: 5 },
          stats: {
            maxHp: 240,
            currentHp: 240,
            maxAp: 6,
            currentAp: 6,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'magma_cataclysm',
              name: 'Magma Cataclysm',
              element: 'Fire',
              icon: '🌋',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 38,
              appliesStatus: 'Burning',
              statusDuration: 3,
              createsHazard: 'Burning',
              hazardDuration: 3,
              description: 'Unleashes devastating magma fissures across the arena.',
              level: 3,
            },
            {
              id: 'titanic_stomp',
              name: 'Titanic Stomp',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 28,
              appliesStatus: 'Rooted',
              statusDuration: 2,
              description: 'Shatters the arena surface, pinning the hero.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
          isBoss: true,
        });

        enemies.push({
          id: 'boss_wisp_1',
          name: 'Flame Wisp',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 7, y: 2 },
          stats: {
            maxHp: 45,
            currentHp: 45,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'ember_spark',
              name: 'Ember Spark',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 18,
              description: 'Sparks of living flame.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'boss_wisp_2',
          name: 'Flame Wisp',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 7, y: 8 },
          stats: {
            maxHp: 45,
            currentHp: 45,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'ember_spark',
              name: 'Ember Spark',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 18,
              description: 'Sparks of living flame.',
              level: 2,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 6:
        // Round 6: Tsunami Shifter + Volt Tempest + Toxic Alchemist
        enemies.push({
          id: 'enemy_r6_1',
          name: 'Tsunami Shifter',
          faction: 'Enemy',
          avatar: '🌊',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 80,
            currentHp: 80,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Water',
          },
          abilities: [
            {
              id: 'crashing_wave',
              name: 'Crashing Wave',
              element: 'Water',
              icon: '🌊',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 30,
              appliesStatus: 'Wet',
              statusDuration: 3,
              createsHazard: 'Puddle',
              hazardDuration: 3,
              description: 'Torrential downpour drenching the ground.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r6_2',
          name: 'Volt Tempest',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 7, y: 5 },
          stats: {
            maxHp: 75,
            currentHp: 75,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'thunder_chain',
              name: 'Thunder Chain',
              element: 'Lightning',
              icon: '⚡',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 34,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Electrifies water puddles and shocks foes.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r6_3',
          name: 'Toxic Alchemist',
          faction: 'Enemy',
          avatar: '🧪',
          coord: { x: 8, y: 7 },
          stats: {
            maxHp: 80,
            currentHp: 80,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Poison',
          },
          abilities: [
            {
              id: 'acid_bomb',
              name: 'Acid Bomb',
              element: 'Poison',
              icon: '🧪',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 28,
              appliesStatus: 'Poisoned',
              statusDuration: 3,
              createsHazard: 'ToxicMire',
              hazardDuration: 3,
              description: 'Vial of toxic reactant.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 7:
        // Round 7: Terramancer High Priest + Miasma Stalker + Obsidian Golem
        enemies.push({
          id: 'enemy_r7_1',
          name: 'Terramancer Priest',
          faction: 'Enemy',
          avatar: '🧙‍♂️',
          coord: { x: 8, y: 3 },
          stats: {
            maxHp: 95,
            currentHp: 95,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Earth',
          },
          abilities: [
            {
              id: 'geo_blast',
              name: 'Geo Blast',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 32,
              appliesStatus: 'Rooted',
              statusDuration: 2,
              description: 'Fires dense subterranean minerals.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r7_2',
          name: 'Obsidian Golem',
          faction: 'Enemy',
          avatar: '🗿',
          coord: { x: 6, y: 5 },
          stats: {
            maxHp: 110,
            currentHp: 110,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Earth',
          },
          abilities: [
            {
              id: 'obsidian_smash',
              name: 'Obsidian Smash',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 2,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 35,
              description: 'Heavy obsidian hammer strike.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r7_3',
          name: 'Miasma Stalker',
          faction: 'Enemy',
          avatar: '🦂',
          coord: { x: 8, y: 8 },
          stats: {
            maxHp: 85,
            currentHp: 85,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Poison',
          },
          abilities: [
            {
              id: 'miasma_sting',
              name: 'Miasma Sting',
              element: 'Poison',
              icon: '🧪',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 30,
              appliesStatus: 'Poisoned',
              statusDuration: 3,
              description: 'Stings with deadly neurotoxin.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 8:
        // Round 8: Void Riftcaller + Chaos Zealot + Abyssal Specter
        enemies.push({
          id: 'enemy_r8_1',
          name: 'Void Riftcaller',
          faction: 'Enemy',
          avatar: '🔮',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 90,
            currentHp: 90,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'rift_surge',
              name: 'Rift Surge',
              element: 'Void',
              icon: '🌌',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 36,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Opens rift into nothingness.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r8_2',
          name: 'Chaos Zealot',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 6, y: 5 },
          stats: {
            maxHp: 90,
            currentHp: 90,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'chaos_blast',
              name: 'Chaos Blast',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 34,
              appliesStatus: 'Burning',
              statusDuration: 3,
              description: 'Volatile blast of hellfire.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r8_3',
          name: 'Abyssal Specter',
          faction: 'Enemy',
          avatar: '👻',
          coord: { x: 8, y: 7 },
          stats: {
            maxHp: 80,
            currentHp: 80,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'abyssal_drain',
              name: 'Abyssal Drain',
              element: 'Void',
              icon: '🟣',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 32,
              description: 'Saps life essence.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 9:
        // Round 9: Apex Stormlord + Abyssal Torrent + Plaguebringer
        enemies.push({
          id: 'enemy_r9_1',
          name: 'Apex Stormlord',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 8, y: 1 },
          stats: {
            maxHp: 95,
            currentHp: 95,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'lightning_strike',
              name: 'Lightning Strike',
              element: 'Lightning',
              icon: '⚡',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 36,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Summons heaven-rending bolt.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r9_2',
          name: 'Abyssal Torrent',
          faction: 'Enemy',
          avatar: '💧',
          coord: { x: 8, y: 4 },
          stats: {
            maxHp: 90,
            currentHp: 90,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Water',
          },
          abilities: [
            {
              id: 'hydrowall',
              name: 'Hydrowall',
              element: 'Water',
              icon: '🌊',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 30,
              createsHazard: 'Puddle',
              hazardDuration: 3,
              appliesStatus: 'Wet',
              statusDuration: 3,
              description: 'Deluges the target in water.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r9_3',
          name: 'Plaguebringer',
          faction: 'Enemy',
          avatar: '🧪',
          coord: { x: 7, y: 7 },
          stats: {
            maxHp: 90,
            currentHp: 90,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Poison',
          },
          abilities: [
            {
              id: 'contagion',
              name: 'Contagion',
              element: 'Poison',
              icon: '🧪',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 30,
              createsHazard: 'ToxicMire',
              hazardDuration: 3,
              appliesStatus: 'Poisoned',
              statusDuration: 3,
              description: 'Spreads noxious contagion.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 10:
        // 👑 BOSS 2 (Round 10): STORM SOVEREIGN - AETHON + 2x Storm Elementals
        enemies.push({
          id: 'boss_storm_sovereign',
          name: 'STORM SOVEREIGN - AETHON (Boss)',
          faction: 'Enemy',
          avatar: '👑',
          coord: { x: 8, y: 5 },
          stats: {
            maxHp: 350,
            currentHp: 350,
            maxAp: 6,
            currentAp: 6,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'maelstrom_deluge',
              name: 'Maelstrom Deluge',
              element: 'Water',
              icon: '🌊',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 40,
              appliesStatus: 'Wet',
              statusDuration: 3,
              createsHazard: 'Puddle',
              hazardDuration: 4,
              description: 'Submerges the battlefield under a ferocious storm deluge.',
              level: 4,
            },
            {
              id: 'chain_lightning_cataclysm',
              name: 'Overcharged Chain Lightning',
              element: 'Lightning',
              icon: '⚡',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 45,
              appliesStatus: 'Shocked',
              statusDuration: 3,
              createsHazard: 'ElectrifiedPuddle',
              hazardDuration: 3,
              description: 'Fires lethal voltage that chains across wet battlefield surfaces.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
          isBoss: true,
        });

        enemies.push({
          id: 'boss_storm_elem_1',
          name: 'Storm Elemental',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 7, y: 2 },
          stats: {
            maxHp: 65,
            currentHp: 65,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'shock_bolt',
              name: 'Shock Bolt',
              element: 'Lightning',
              icon: '⚡',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 25,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Snapping lightning bolt.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'boss_storm_elem_2',
          name: 'Storm Elemental',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 7, y: 8 },
          stats: {
            maxHp: 65,
            currentHp: 65,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'shock_bolt',
              name: 'Shock Bolt',
              element: 'Lightning',
              icon: '⚡',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 25,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Snapping lightning bolt.',
              level: 3,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 11:
        // Round 11: Void Siphon + Supernova Pyromancer + Charged Behemoth
        enemies.push({
          id: 'enemy_r11_1',
          name: 'Void Siphon',
          faction: 'Enemy',
          avatar: '🌌',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 110,
            currentHp: 110,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'entropy_drain',
              name: 'Entropy Drain',
              element: 'Void',
              icon: '🌌',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 38,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Drains cosmic essence.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r11_2',
          name: 'Supernova Pyromancer',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 7, y: 5 },
          stats: {
            maxHp: 105,
            currentHp: 105,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'supernova_beam',
              name: 'Supernova Beam',
              element: 'Fire',
              icon: '🔥',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 40,
              createsHazard: 'Burning',
              hazardDuration: 3,
              appliesStatus: 'Burning',
              statusDuration: 3,
              description: 'Incinerating cosmic heat.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r11_3',
          name: 'Charged Behemoth',
          faction: 'Enemy',
          avatar: '🦏',
          coord: { x: 8, y: 7 },
          stats: {
            maxHp: 120,
            currentHp: 120,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'plasma_charge',
              name: 'Plasma Charge',
              element: 'Lightning',
              icon: '⚡',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 36,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Electrified tackle.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 12:
        // Round 12: Pestilence Overlord + Earth Titan + Dark Matter Shade
        enemies.push({
          id: 'enemy_r12_1',
          name: 'Pestilence Overlord',
          faction: 'Enemy',
          avatar: '🧪',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 120,
            currentHp: 120,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Poison',
          },
          abilities: [
            {
              id: 'plague_eruption',
              name: 'Plague Eruption',
              element: 'Poison',
              icon: '🧪',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 40,
              createsHazard: 'ToxicMire',
              hazardDuration: 3,
              appliesStatus: 'Poisoned',
              statusDuration: 3,
              description: 'Erupts toxic rot across the floor.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r12_2',
          name: 'Earth Titan',
          faction: 'Enemy',
          avatar: '🗿',
          coord: { x: 6, y: 5 },
          stats: {
            maxHp: 140,
            currentHp: 140,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Earth',
          },
          abilities: [
            {
              id: 'tectonic_crush',
              name: 'Tectonic Crush',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 42,
              appliesStatus: 'Rooted',
              statusDuration: 2,
              description: 'Crushes targets under shifting plates.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r12_3',
          name: 'Dark Matter Shade',
          faction: 'Enemy',
          avatar: '🌌',
          coord: { x: 8, y: 8 },
          stats: {
            maxHp: 115,
            currentHp: 115,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'null_beam',
              name: 'Null Beam',
              element: 'Void',
              icon: '🟣',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 38,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Beam of pure annihilation.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 13:
        // Round 13: 4x Ascended Elementalists (Fire, Water, Lightning, Earth)
        enemies.push({
          id: 'enemy_r13_1',
          name: 'Ascended Pyromancer',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 8, y: 1 },
          stats: {
            maxHp: 110,
            currentHp: 110,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'hellfire_beam',
              name: 'Hellfire Beam',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 38,
              createsHazard: 'Burning',
              hazardDuration: 2,
              appliesStatus: 'Burning',
              statusDuration: 3,
              description: 'Hellfire lance.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r13_2',
          name: 'Ascended Aquamancer',
          faction: 'Enemy',
          avatar: '💧',
          coord: { x: 8, y: 4 },
          stats: {
            maxHp: 110,
            currentHp: 110,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Water',
          },
          abilities: [
            {
              id: 'tidal_crush',
              name: 'Tidal Crush',
              element: 'Water',
              icon: '🌊',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 36,
              createsHazard: 'Puddle',
              hazardDuration: 3,
              appliesStatus: 'Wet',
              statusDuration: 3,
              description: 'Pressurized water torrent.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r13_3',
          name: 'Ascended Fulgurite',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 8, y: 7 },
          stats: {
            maxHp: 105,
            currentHp: 105,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'thunder_javelin',
              name: 'Thunder Javelin',
              element: 'Lightning',
              icon: '⚡',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 42,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Ionized spear of high voltage.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r13_4',
          name: 'Ascended Terramancer',
          faction: 'Enemy',
          avatar: '🪨',
          coord: { x: 6, y: 5 },
          stats: {
            maxHp: 130,
            currentHp: 130,
            maxAp: 4,
            currentAp: 4,
            moveCostPerTile: 1,
            elementalAffinity: 'Earth',
          },
          abilities: [
            {
              id: 'monolith_smash',
              name: 'Monolith Smash',
              element: 'Earth',
              icon: '🪨',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 38,
              appliesStatus: 'Rooted',
              statusDuration: 2,
              description: 'Drops monolithic stone.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 14:
        // Round 14: 2x Void Nullifiers + Prime Fire Conduit
        enemies.push({
          id: 'enemy_r14_1',
          name: 'Void Nullifier',
          faction: 'Enemy',
          avatar: '🌌',
          coord: { x: 8, y: 2 },
          stats: {
            maxHp: 130,
            currentHp: 130,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'null_rupture',
              name: 'Null Rupture',
              element: 'Void',
              icon: '🌌',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 44,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Tears cosmic fabric.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r14_2',
          name: 'Void Nullifier',
          faction: 'Enemy',
          avatar: '🌌',
          coord: { x: 8, y: 7 },
          stats: {
            maxHp: 130,
            currentHp: 130,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'null_rupture',
              name: 'Null Rupture',
              element: 'Void',
              icon: '🌌',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 44,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Tears cosmic fabric.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'enemy_r14_3',
          name: 'Prime Fire Conduit',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 7, y: 4 },
          stats: {
            maxHp: 125,
            currentHp: 125,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'conduit_fire',
              name: 'Conduit Firestorm',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 40,
              createsHazard: 'Burning',
              hazardDuration: 3,
              appliesStatus: 'Burning',
              statusDuration: 3,
              description: 'Raging storm of pure fire.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 15:
        // 👑 BOSS 3 (Round 15 FINAL BOSS): THE VOID ARCHON - SUPREME OVERLORD + 2x Void Reapers
        enemies.push({
          id: 'boss_void_archon',
          name: 'THE VOID ARCHON (Supreme Boss)',
          faction: 'Enemy',
          avatar: '👑',
          coord: { x: 8, y: 5 },
          stats: {
            maxHp: 480,
            currentHp: 480,
            maxAp: 7,
            currentAp: 7,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'cosmic_singularity',
              name: 'Cosmic Singularity',
              element: 'Void',
              icon: '🌌',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 48,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              description: 'Tears a massive singularity in reality causing entropic annihilation.',
              level: 5,
            },
            {
              id: 'dimensional_collapse',
              name: 'Dimensional Collapse',
              element: 'Void',
              icon: '🟣',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 44,
              description: 'Collapses surrounding space in an apocalyptic pulse.',
              level: 5,
            },
          ],
          statusEffects: [],
          isDead: false,
          isBoss: true,
        });

        enemies.push({
          id: 'boss_reaper_1',
          name: 'Void Reaper',
          faction: 'Enemy',
          avatar: '💀',
          coord: { x: 7, y: 2 },
          stats: {
            maxHp: 80,
            currentHp: 80,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'reaper_scythe',
              name: 'Reaper Scythe',
              element: 'Void',
              icon: '🖤',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 30,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Dark scythe reap.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'boss_reaper_2',
          name: 'Void Reaper',
          faction: 'Enemy',
          avatar: '💀',
          coord: { x: 7, y: 8 },
          stats: {
            maxHp: 80,
            currentHp: 80,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'reaper_scythe',
              name: 'Reaper Scythe',
              element: 'Void',
              icon: '🖤',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 3,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 30,
              appliesStatus: 'VoidMarked',
              statusDuration: 3,
              description: 'Dark scythe reap.',
              level: 4,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      case 1000:
        // Round 1000: THE VOID OVERLORD (Ultimate Boss - Reclaim Stolen Magic)
        enemies.push({
          id: 'boss_void_overlord_r1000',
          name: 'THE VOID OVERLORD (Ultimate Boss)',
          faction: 'Enemy',
          avatar: '😈🌌👑',
          coord: { x: 8, y: 5 },
          stats: {
            maxHp: 25000,
            currentHp: 25000,
            maxAp: 6,
            currentAp: 6,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'overlord_siphon_stolen_magic',
              name: 'Siphon of Stolen Magic',
              element: 'Void',
              icon: '😈',
              apCost: 2,
              cooldown: 1,
              currentCooldown: 0,
              range: 6,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 120,
              appliesStatus: 'Burning',
              statusDuration: 3,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              description: 'Channels the stolen primal magic of the Grand Wizard into a devastating cosmic beam.',
              level: 10,
            },
            {
              id: 'overlord_singularity_crush',
              name: 'Cosmic Singularity Crush',
              element: 'Void',
              icon: '🌌',
              apCost: 3,
              cooldown: 2,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 150,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              description: 'Collapses spacetime around the hero with crushing void gravity.',
              level: 10,
            },
            {
              id: 'overlord_void_cataclysm',
              name: 'Void Sovereign Cataclysm',
              element: 'Void',
              icon: '👑',
              apCost: 3,
              cooldown: 3,
              currentCooldown: 0,
              range: 6,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 180,
              description: 'The supreme reality-shattering finishing strike of the Void Overlord.',
              level: 10,
            },
          ],
          statusEffects: [],
          isDead: false,
          isBoss: true,
        });

        // Round 1000 has NO minions - The Void Overlord fights alone
        break;

      case 5000:
        // Round 5000: THE VOID OVERLORD (10x Ascended God - 10 Times More Powerful!)
        enemies.push({
          id: 'boss_void_overlord_r5000',
          name: 'THE VOID OVERLORD (10x Ascended God)',
          faction: 'Enemy',
          avatar: '😈🌌👑💥',
          coord: { x: 8, y: 5 },
          stats: {
            maxHp: 250000, // 10x 25,000 HP
            currentHp: 250000,
            maxAp: 8,
            currentAp: 8,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'overlord_10x_siphon_stolen_magic',
              name: '10x Siphon of Annihilation',
              element: 'Void',
              icon: '😈',
              apCost: 2,
              cooldown: 1,
              currentCooldown: 0,
              range: 6,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 1200, // 10x 120
              appliesStatus: 'Burning',
              statusDuration: 3,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              description: 'Channels catastrophic 10x augmented stolen cosmic magic.',
              level: 25,
            },
            {
              id: 'overlord_10x_singularity_crush',
              name: '10x Supermassive Singularity',
              element: 'Void',
              icon: '🌌',
              apCost: 3,
              cooldown: 2,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 1500, // 10x 150
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              description: 'Tears a supermassive black hole with 10x crushing void pressure.',
              level: 25,
            },
            {
              id: 'overlord_10x_void_cataclysm',
              name: '10x Omniversal Cataclysm',
              element: 'Void',
              icon: '👑',
              apCost: 3,
              cooldown: 3,
              currentCooldown: 0,
              range: 6,
              aoeRadius: 2,
              targeting: 'SingleUnit',
              baseDamage: 1800, // 10x 180
              description: 'The supreme universe-obliterating 10x finishing cataclysm of the Ascended Void Overlord.',
              level: 25,
            },
          ],
          statusEffects: [],
          isDead: false,
          isBoss: true,
        });

        // Round 5000 has NO minions - The 10x Void Overlord fights alone
        break;

      case 30:
        // Round 30: The Celestial Fusion Crucible (Milestone Essence Merge Sanctuary)
        enemies.push({
          id: 'boss_r30_crucible_archon',
          name: 'CELESTIAL CRUCIBLE ARCHON (Fusion Altar Sovereign)',
          faction: 'Enemy',
          avatar: '🌟',
          coord: { x: 8, y: 5 },
          stats: {
            maxHp: 2400,
            currentHp: 2400,
            maxAp: 8,
            currentAp: 8,
            moveCostPerTile: 1,
            elementalAffinity: 'Energy',
          },
          abilities: [
            {
              id: 'crucible_cataclysm',
              name: 'Crucible Cataclysm',
              element: 'Energy',
              icon: '🌟',
              apCost: 3,
              cooldown: 0,
              currentCooldown: 0,
              range: 6,
              aoeRadius: 2,
              targeting: 'SingleUnit',
              baseDamage: 90,
              description: 'Unleashes raw celestial energy across the crucible battlefield.',
              level: 10,
            },
            {
              id: 'essence_singularity',
              name: 'Essence Singularity',
              element: 'Void',
              icon: '🌀',
              apCost: 2,
              cooldown: 1,
              currentCooldown: 0,
              range: 5,
              aoeRadius: 1,
              targeting: 'SingleUnit',
              baseDamage: 75,
              createsHazard: 'VoidRift',
              hazardDuration: 3,
              description: 'Collapses space, drawing victims into the vortex.',
              level: 10,
            },
          ],
          statusEffects: [],
          isDead: false,
          isBoss: true,
        });

        // 3x Crucible Essence Keepers (guaranteeing essence drops for merging)
        enemies.push({
          id: 'escort_r30_fire_keeper',
          name: 'Crucible Fire Keeper',
          faction: 'Enemy',
          avatar: '🔥',
          coord: { x: 7, y: 2 },
          stats: {
            maxHp: 650,
            currentHp: 650,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Fire',
          },
          abilities: [
            {
              id: 'fire_crucible_blast',
              name: 'Infernal Blast',
              element: 'Fire',
              icon: '🔥',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 45,
              createsHazard: 'Burning',
              hazardDuration: 2,
              description: 'Strikes with concentrated molten flame.',
              level: 8,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'escort_r30_void_keeper',
          name: 'Crucible Void Keeper',
          faction: 'Enemy',
          avatar: '🌌',
          coord: { x: 7, y: 8 },
          stats: {
            maxHp: 650,
            currentHp: 650,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Void',
          },
          abilities: [
            {
              id: 'void_crucible_blast',
              name: 'Void Sever',
              element: 'Void',
              icon: '🌌',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 48,
              description: 'Strikes with cosmic void essence.',
              level: 8,
            },
          ],
          statusEffects: [],
          isDead: false,
        });

        enemies.push({
          id: 'escort_r30_lightning_keeper',
          name: 'Crucible Lightning Keeper',
          faction: 'Enemy',
          avatar: '⚡',
          coord: { x: 6, y: 5 },
          stats: {
            maxHp: 650,
            currentHp: 650,
            maxAp: 5,
            currentAp: 5,
            moveCostPerTile: 1,
            elementalAffinity: 'Lightning',
          },
          abilities: [
            {
              id: 'lightning_crucible_bolt',
              name: 'Ionic Discharge',
              element: 'Lightning',
              icon: '⚡',
              apCost: 2,
              cooldown: 0,
              currentCooldown: 0,
              range: 4,
              aoeRadius: 0,
              targeting: 'SingleUnit',
              baseDamage: 46,
              appliesStatus: 'Shocked',
              statusDuration: 2,
              description: 'Discharges high-voltage ionization.',
              level: 8,
            },
          ],
          statusEffects: [],
          isDead: false,
        });
        break;

      default:
        // Procedural generation for round > 15 up to 1000
        const isBossRound = round % 5 === 0;
        const progressFactor = Math.min(1, Math.max(0, (round - 15) / 985));
        // HP scales progressively from 1.0x up to 4.5x
        const hpMultiplier = 1 + progressFactor * 3.5;
        // Damage scales conservatively from 1.0x to 2.0x so hero HP pool remains viable
        const damageMultiplier = 1 + progressFactor * 1.0;

        if (isBossRound) {
          const bossHp = Math.floor(400 * hpMultiplier);
          const bossAffinity: ElementType = ['Fire', 'Lightning', 'Void', 'Water', 'Earth', 'Poison'][
            Math.floor(round / 5) % 6
          ] as ElementType;

          const isR100Overlord = round === 100;
          enemies.push({
            id: isR100Overlord ? 'boss_void_overlord_r100' : `procedural_boss_r${round}`,
            name: isR100Overlord ? 'THE VOID OVERLORD (Tier 20 Boss)' : `PRIMORDIAL OVERLORD (Tier ${Math.floor(round / 5)} Boss)`,
            faction: 'Enemy',
            avatar: isR100Overlord ? '😈🌌👑' : '👑',
            coord: { x: 8, y: 5 },
            stats: {
              maxHp: bossHp,
              currentHp: bossHp,
              maxAp: 6,
              currentAp: 6,
              moveCostPerTile: 1,
              elementalAffinity: bossAffinity,
            },
            abilities: [
              {
                id: `boss_primordial_blast_${round}`,
                name: 'Primordial Cataclysm',
                element: bossAffinity,
                icon: '💥',
                apCost: 3,
                cooldown: 1,
                currentCooldown: 0,
                range: 5,
                aoeRadius: 1,
                targeting: 'SingleUnit',
                baseDamage: Math.floor(35 * damageMultiplier),
                createsHazard: bossAffinity === 'Fire' ? 'Burning' : bossAffinity === 'Water' ? 'Puddle' : bossAffinity === 'Void' ? 'VoidRift' : 'ToxicMire',
                hazardDuration: 3,
                description: 'Unleashes raw primordial calamity.',
                level: Math.min(10, Math.floor(round / 3)),
              },
            ],
            statusEffects: [],
            isDead: false,
            isBoss: true,
          });

          // 2x Scaled Escorts
          enemies.push({
            id: `procedural_escort_1_${round}`,
            name: 'Ascended Guardian',
            faction: 'Enemy',
            avatar: '👾',
            coord: { x: 7, y: 2 },
            stats: {
              maxHp: Math.floor(85 * hpMultiplier),
              currentHp: Math.floor(85 * hpMultiplier),
              maxAp: 4,
              currentAp: 4,
              moveCostPerTile: 1,
              elementalAffinity: bossAffinity,
            },
            abilities: [
              {
                id: `escort_strike_1_${round}`,
                name: 'Ascended Blast',
                element: bossAffinity,
                icon: '⚡',
                apCost: 2,
                cooldown: 1,
                currentCooldown: 0,
                range: 4,
                aoeRadius: 0,
                targeting: 'SingleUnit',
                baseDamage: Math.floor(20 * damageMultiplier),
                description: 'Focused elemental energy.',
                level: Math.floor(round / 4),
              },
            ],
            statusEffects: [],
            isDead: false,
          });

          enemies.push({
            id: `procedural_escort_2_${round}`,
            name: 'Ascended Guardian',
            faction: 'Enemy',
            avatar: '👾',
            coord: { x: 7, y: 8 },
            stats: {
              maxHp: Math.floor(85 * hpMultiplier),
              currentHp: Math.floor(85 * hpMultiplier),
              maxAp: 4,
              currentAp: 4,
              moveCostPerTile: 1,
              elementalAffinity: bossAffinity,
            },
            abilities: [
              {
                id: `escort_strike_2_${round}`,
                name: 'Ascended Blast',
                element: bossAffinity,
                icon: '⚡',
                apCost: 2,
                cooldown: 1,
                currentCooldown: 0,
                range: 4,
                aoeRadius: 0,
                targeting: 'SingleUnit',
                baseDamage: Math.floor(20 * damageMultiplier),
                description: 'Focused elemental energy.',
                level: Math.floor(round / 4),
              },
            ],
            statusEffects: [],
            isDead: false,
          });
        } else {
          // Standard Scaled Enemy Squad
          const elements: ElementType[] = ['Fire', 'Water', 'Lightning', 'Earth', 'Poison', 'Void'];
          for (let i = 0; i < 3; i++) {
            const elem = elements[(round + i) % elements.length];
            const hp = Math.floor((75 + i * 15) * hpMultiplier);
            enemies.push({
              id: `procedural_enemy_${round}_${i}`,
              name: `Ascended ${elem} Adept`,
              faction: 'Enemy',
              avatar: elem === 'Fire' ? '🔥' : elem === 'Water' ? '💧' : elem === 'Lightning' ? '⚡' : elem === 'Earth' ? '🪨' : elem === 'Poison' ? '🧪' : '🌌',
              coord: { x: 8 - Math.floor(i / 2), y: 2 + i * 3 },
              stats: {
                maxHp: hp,
                currentHp: hp,
                maxAp: 4,
                currentAp: 4,
                moveCostPerTile: 1,
                elementalAffinity: elem,
              },
              abilities: [
                {
                  id: `proc_spell_${round}_${i}`,
                  name: `${elem} Strike`,
                  element: elem,
                  icon: '✨',
                  apCost: 2,
                  cooldown: 0,
                  currentCooldown: 0,
                  range: 4,
                  aoeRadius: 0,
                  targeting: 'SingleUnit',
                  baseDamage: Math.floor(22 * damageMultiplier),
                  description: `Potent surge of ${elem} magic.`,
                  level: Math.floor(round / 4),
                },
              ],
              statusEffects: [],
              isDead: false,
            });
          }
        }
        break;
    }

    return enemies.map((enemy) => upgradeToCPUChampion(enemy, round));
  }

  public getAvailableUpgrades(): {
    abilities: Ability[];
    relics: PassiveRelic[];
  } {
    const abilities: Ability[] = [
      {
        id: 'toxic_cloud',
        name: 'Toxic Cloud',
        element: 'Poison',
        icon: '🧪',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 24,
        appliesStatus: 'Poisoned',
        statusDuration: 3,
        createsHazard: 'ToxicMire',
        hazardDuration: 3,
        description: 'Blasts an area with toxic spores creating Toxic Mire.',
        level: 1,
      },
      {
        id: 'tectonic_quake',
        name: 'Tectonic Quake',
        element: 'Earth',
        icon: '🪨',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 32,
        appliesStatus: 'Rooted',
        statusDuration: 2,
        description: 'Shatters the ground, damaging and rooting enemies.',
        level: 1,
      },
      {
        id: 'void_rupture',
        name: 'Void Rupture',
        element: 'Void',
        icon: '🌌',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 40,
        appliesStatus: 'VoidMarked',
        statusDuration: 3,
        createsHazard: 'VoidRift',
        hazardDuration: 3,
        description: 'Ruptures reality for high entropic burst damage.',
        level: 1,
      },
      {
        id: 'inferno_pillar',
        name: 'Inferno Pillar',
        element: 'Fire',
        icon: '🔥',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 38,
        appliesStatus: 'Burning',
        statusDuration: 3,
        createsHazard: 'Burning',
        hazardDuration: 3,
        description: 'Summons a pillar of roaring flames.',
        level: 1,
      },
      {
        id: 'chain_overload',
        name: 'Chain Overload',
        element: 'Lightning',
        icon: '⚡',
        apCost: 3,
        cooldown: 1,
        currentCooldown: 0,
        range: 5,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 36,
        appliesStatus: 'Shocked',
        statusDuration: 2,
        description: 'Blasts ionized lightning that shocks all nearby enemies.',
        level: 1,
      },
      {
        id: 'glacial_burst',
        name: 'Glacial Burst',
        element: 'Water',
        icon: '💧',
        apCost: 2,
        cooldown: 1,
        currentCooldown: 0,
        range: 4,
        aoeRadius: 1,
        targeting: 'SingleUnit',
        baseDamage: 28,
        appliesStatus: 'Wet',
        statusDuration: 3,
        createsHazard: 'Puddle',
        hazardDuration: 3,
        description: 'Freezes pressurized water, leaving large puddles.',
        level: 1,
      },
    ];

    const relics: PassiveRelic[] = [
      {
        id: 'arcane_battery',
        name: 'Arcane Battery',
        icon: '🔋',
        description: '+2 Max Action Points per turn',
        costEssence: 40,
        costXp: 50,
        applied: false,
        effect: (hero: Unit) => {
          hero.stats.maxAp += 2;
          hero.stats.currentAp += 2;
        },
      },
      {
        id: 'vitality_crystal',
        name: 'Vitality Crystal',
        icon: '💎',
        description: '+40 Max HP and restores full health',
        costEssence: 35,
        costXp: 40,
        applied: false,
        effect: (hero: Unit) => {
          hero.stats.maxHp += 40;
          hero.stats.currentHp = hero.stats.maxHp;
        },
      },
      {
        id: 'elemental_prism',
        name: 'Elemental Prism',
        icon: '🔮',
        description: 'Reduces AP cost of all spells by 1 (min 1)',
        costEssence: 60,
        costXp: 75,
        applied: false,
        effect: (hero: Unit) => {
          hero.abilities.forEach((a) => {
            a.apCost = Math.max(1, a.apCost - 1);
          });
        },
      },
      {
        id: 'phoenix_feather',
        name: 'Phoenix Feather',
        icon: '🪶',
        description: '+50 Max HP and +1 Max AP',
        costEssence: 55,
        costXp: 60,
        applied: false,
        effect: (hero: Unit) => {
          hero.stats.maxHp += 50;
          hero.stats.currentHp = hero.stats.maxHp;
          hero.stats.maxAp += 1;
          hero.stats.currentAp += 1;
        },
      },
      {
        id: 'elemental_catalyst',
        name: 'Elemental Catalyst',
        icon: '⚡',
        description: 'Empowers all abilities with +8 Base Damage',
        costEssence: 50,
        costXp: 65,
        applied: false,
        effect: (hero: Unit) => {
          hero.abilities.forEach((a) => {
            a.baseDamage += 8;
          });
        },
      },
    ];

    return { abilities, relics };
  }
}
